### ISSUE TITLE
editable tables in view mode

### ISSUE THREAD

**Issue by dtcg** [stefan-niedermann/nextcloud-notes#1041]
Thanks so much for releasing the long-awaited table feature!

Now, as a table grows in size over time, it becomes less and less practical to edit it through code, even markdown. 

If a cell was directy editable in view mode as we tap it, it would make the whole table mechanics more efficient. A bit like ticking to-do lists in view mode.

🥇 Stay FLOSS everyone 🥇

**Comment by stefan-niedermann** [comment]
Sorry to disappoint you, but this will not happen.

While the editing mode is not destructive but keeps the markdown punctuation, the preview mode *is* destructive. This means once you have a rendered view, let's say with list items, you will for example not know whether a list has been generated with

```
- Item
* Item
+ Item
```

This makes a **lossless** editing impossible.

Checkboxes can be toggled because we try to match the source with the final rendered view - actually it's more a guess. We try to count the ceckboxes which are there and then toggle it in the source. Alone this feature, while it seems to be easy, has lots of pitfalls, for example we have to detect checkboxes in codeblocks which *aren't* rendered.

Editing losslessly in a the preview mode will therefore never come.

Pull Requests to enhance the editor on the other side, which keeps the punctuation, are welcome of course 😉
