### ISSUE TITLE
Pure WebDAV Sync

### ISSUE THREAD

**Issue by MisterY** [stefan-niedermann/nextcloud-notes#1044]
**Is your feature request related to a problem? Please describe.**
I have a collection of notes outside my NextCloud instance and would prefer to keep it there. The notes are accessible via a WebDAV interface. I cannot find a decent alternative to NextCloud Notes and would like to use it with my Notes collection without migrating them to my NextCloud instance.

**Describe the solution you'd like**
I would very much appreciate a possibility to enter the Notes root and have the app work via WebDAV with any other source, not only NextCloud.

**Describe alternatives you've considered**
The different apps (i.e. Joplin) I have tried are either unreliable, have sync issues, or the features and aesthetics of the app are not up to par with NC Notes app.
My preference would be to use an Open Source app.
In the past, I have also used NextCloud Notes but, due to limited storage and throughput of the NC instance, I would prefer to keep the notes at a location with higher limits. There is a lot of data in the collections, including attachments, images, videos, etc.

**Additional context**
None so far.  Hope the request is clear. It may be a bit unusual and I could not find any references to WebDAV in the issue history.
Thanks for all the work so far!

**Comment by stefan-niedermann** [comment]
Dear @MisterY,

thank you for the request. Unfortunately this is out of scope for this project for various reasons, mainly because we completely rely on the Nextcloud SSO. This means that we don't have any network stack at all, but completely rely on the Nextcloud app - on the other hand we don't have to maintain any self signed certificate stuff and can support various edge cases of server setups out of the box.

Maybe you can try to mount your external drive via WebDAV on the server side into the `/Notes` folder, so you still are able to access them with this app.

**Comment by MisterY** [comment]
Thanks for the tip. Earlier on, I did not see an option to mount this, although it would make perfect sense. Now I am digging a bit deeper and will add some links here for the reference, should anyone have a similar case in the future:

- https://docs.nextcloud.com/server/20/admin_manual/configuration_files/external_storage/webdav.html

**Comment by stefan-niedermann** [comment]
Yeah, well maybe you could ask in the repository of the notes server app whether this is a supported scenario
