### ISSUE TITLE
Show DisplayName instead of uid attribute for LDAP users

### ISSUE THREAD

**Issue by ke-lin** [stefan-niedermann/nextcloud-notes#1079]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**

The Notes App shows the uid attribute of LDAP users, which is a long cryptic string. This makes switching between different accounts difficult and does not look so nice. 

**Describe the solution you'd like**

It would be nice to use the DisplayName attribute for LDAP user for the app "username" attribute, instead of the uid.

**Comment by MasterWanna** [comment]
Hi, developer. Does this issue still need to fix since the similar issue is closed in nextcloud-deck?

**Comment by stefan-niedermann** [comment]
Yes, in Notes this issue still exists. It was a bit easier in Deck because we already called the correct endpoint which we are not yet doing in the Notes app. Additionally we just had a 7000 code lines refactoring and more work in progress, so it will take some time more to implement this for the Notes app.

**Comment by MasterWanna** [comment]
Thanks, and I would try to fix this in a few days similarly to method in nextcloud-deck.

**Comment by stefan-niedermann** [comment]
Sorry, i don't understand this...?

**Comment by MasterWanna** [comment]
Oh, I got it. Is it that add `displayName` into `Account`, when switching accout, we should show `displayName` instead of `userName` and add a property `displayName` for the fetching of the account in `Capabilities`?

**Comment by stefan-niedermann** [comment]
>  Is it that add displayName into Account

:heavy_check_mark: 

> when switching accout, we should show displayName instead of userName

:heavy_check_mark: 

> add a property displayName for the fetching of the account in Capabilities

When fetching the `capabilities` endpoint via a `REST` call, we will additionally need to fetch the `users` endpoint, because the `capabilities` endpoint does not return the display name. It will be simply one `HTTP` call more and the result can be written into `Accounts.displayName` then.

**Comment by stefan-niedermann** [comment]
> For that, I think it maybe changed by the user on local device and just save into displayName each time.

It is not supposed to be editable on the local device

> I have one more question that where should I fetch the displayName?

I don't know yet which endpoint it exactly is, you'll have to check out where the `user` endpoint is in the Deck app or check out the Nextcloud developer manual :)

**Comment by MasterWanna** [comment]
Ok, I got it, it needs an overall consideration.

**Comment by stefan-niedermann** [comment]
Will be fixed in `v3.4.2`.
