### ISSUE TITLE
Note list widget switched to Light mode

### ISSUE THREAD

**Issue by kukukk** [stefan-niedermann/nextcloud-notes#1090]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

I'm using dark mode, and the Note list widget was also using dark mode. After upgrading to v3.2.3 and restarting my phone the widget switched to Light mode. Even if I remove and add again, I can't set to use Dark mode 

**To Reproduce**
1. Choose Dark mode in Settings 
2. Add Note list widget
3. The widget does not ask which mode to use
4. The widget is using Light mode

**Expected behavior**

Note list widget using Dark mode

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 
 - F-Droid or Play Store: Play store 
 - Android-Version: 9, security patch level September 1, 2019
 - Device: Sony Xperia XZ1 Compact 

**Server**
 - Nextcloud version: 20.0.7
 - Nextcloud Notes version (server app): 4.0.2

**Stacktrace**

**Comment by stefan-niedermann** [comment]
The widgets are using the global Android setting since version v3.2.0 (as mentioned in the release notes). You can change it in the Android settings, depending on your manufacturer probably under the "Display" item:

![Screenshot_20210314-175555_Settings](https://user-images.githubusercontent.com/4741199/111076875-8c8bff00-84ee-11eb-8052-b086c8e143b3.png)

The main reason is a better and tighter integration in the default android theming mechanism. For example Android will switch the complete system UI to a dark mode when the battery is low. The widgets have previously not respected those Android intentions, also they ignored the user setting mentioned above for a overall-same theme on the device.

The same applies to the widgets of the Nextcloud Deck App and the Nextcloud News App.

I know this change might not be optimal for every user, but we will keep it this way for now - we discussed this with the other Android app developers and came to the conclusion, that the widget should respect the devices theme.

**Comment by pancan21** [comment]
Indeed the workaroud is working! Thanks!
With the app Dark Mode suggested [in this XDA post](https://www.xda-developers.com/enable-dark-themes-some-android-apps-older-android-versions/) it was even with Android 6.0 possible in contradiction to the information in the previous posts.
