### ISSUE TITLE
Widgets not matching theme 

### ISSUE THREAD

**Issue by zcdunn** [stefan-niedermann/nextcloud-notes#1093]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Widgets don't match the theme selected in app. I use the dark theme and recently my widgets switched to a white theme. 

**To Reproduce**
1. Set your theme to dark
2. Add a widget to your homescreen

**Expected behavior**

The widget theme matches the app

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.2.1
 - F-Droid or Play Store: 1.11
 - Android-Version: 8.0.0
 - Device: Moto G6

**Server**
 - Nextcloud version: 
 - Nextcloud Notes version (server app): 
I'm on mobile right now. Will check this when back at a computer

**Stacktrace**
None

**Comment by stefan-niedermann** [comment]
See https://github.com/stefan-niedermann/nextcloud-notes/issues/1090#issuecomment-798942023

**Comment by zcdunn** [comment]
So for users without a global android theme setting, there's no way to change this now?

**Comment by stefan-niedermann** [comment]
While there are [some tweaks](https://www.androidauthority.com/night-mode-on-android-886864/) which go back to Android 7, your assumption is basically correct. According to the Play Store statistics, more than `73%` of our (Play Store) users have Android 10 or 11 and therefore the setting already present. Further `24%` have Android 7 - Android 9 and can in theory use the linked tweak (or other workarounds if they prefer to stay on old and partially even by Google [abandoned Android versions without security fixes](https://endoflife.date/android) instead of using a modern Custom ROM or other alternatives).

I know this decision is not popular for everyone but the efforts and benefits of a) maintaining a custom hacky dark mode vs. b) supporting natively the global dark mode inclusive auto-theming on low battery etc. is in absolutely no proportion anymore.
