### ISSUE TITLE
Add option for pure black in dark theme=

### ISSUE THREAD

**Issue by Samonitari** [stefan-niedermann/nextcloud-notes#1101]
I'd like to re-open this with a slightly changed suggestion: #557

You quote [UX Planet](https://uxplanet.org/8-tips-for-dark-theme-design-8dfc2f8f7ab6), however their opinion is pretty much flawed - almost amateourish - I think:
- If the too much contrast is the reason, than it can be lowered just as much by making content/light less bright, not just making the background brighter
- Even if you use pure black, most of the time it won't be pure black because of environmental lights
- At least where no readable content is displayed - i.e.: background of the new grid view's stickers (which is very nice BTW) - it makes literally *nothing* more readable
- Multiple manufacturers' ROM use pure black, and they are quite liked. I myself use MIUI.

**Describe the solution you'd like**
The current settings (dark/bright/follow system) is quite good as it is.
The best apps - in this regard - use a separate setting, something like "use true black for dark theme". This way you can have your cake and eat it too.

If you decide to close this request without implementating, that's fine too, it's your project, your decisions.
Thanks for this app, anyway!

**Comment by stefan-niedermann** [comment]
Sadly, no, i haven't changed my mind. Though i have thought a few days about it, and i want to try explain my reasons so you understand that it ain't just for fun.

I have a feeling that the "true" black discussion is more kind of a matter of ideology than of actual facts. I strongly doubt that switching the color from `#121212` to `#000000` will give you even a second more battery life.

> The best apps - in this regard - use a separate setting, something like "use true black for dark theme".

Those apps propably have bit more manpower than a one-man-sunday-afternoon-show to developer *and* maintain those features.

And here we come to the main issue: Android provides native support for a light and a dark variant (`day` / `night` mode). There is no `day` / `night` / `gate to hell` mode, so we would need to completely write the theming stuff ourself (like in the good old Android 4 ages 😄) and i simply can not maintain this stuff for years *and* develop new features from time to time.

So, as long as Android does natively only support two theme modes, we will stay with the current approach. It is not only UX Planet which recommends to avoid pure black (as default, if one doesn't implement a third theme option himself), it is also a Material Design specification as stated in the linked blog post.

**Comment by Samonitari** [comment]
Thanks for the reply I appreciate your sunday-afternoon efforts!

I acknowledge your decision - and what could I do even if I don't - and I will not request it again.
But let me argue a bit on a final note.

> I have a feeling that the "true" black discussion is more kind of a matter of ideology than of actual facts. I strongly doubt that switching the color from `#121212` to `#000000` will give you even a second more battery life.

Here is the [first relevant scientific article I could find in 2 minutes](https://www.hindawi.com/journals/misy/2016/6575931/)

Data shows 20% display energy saving due to less detail and luminosity lowering, and multiplying that with my 17% screen battery usage (and I use true black in most places) that's about 4 percent.

Lighting up pixels (if you are not gaming or running a lot of app) is one of THE most resource energy hungry stuff Another empiric way: measure night time percentage drop with and without always on display. Measure again with more content.

You could argue your app is not eating any significant part on most phones and you are right. If it's about "feeling" and "strongly doubting": I feel designers are not as scientifically grounded as they project, and I strongly doubt they are setting the best examples. Google can be - and have been -  wrong too. Once again: I have never had problems with MIUI's tremendous blackness.

**Comment by stefan-niedermann** [comment]
> Here is the first relevant scientific article I could find in 2 minutes

Thank you for the link, i read the article and it is really interesting. While it is nothing new on AMOLED displays requiring less energy to display darker colors, it is an amazing idea apply this approach for less interesting parts of an image.

>  If it's about "feeling" and "strongly doubting" [...] Google can be - and have been - wrong too

Regarding the feelings: Well, after all we are humans and one can not deny that every decision we make is at least partially influenced by personal feelings, experiences and opinions. Though i try to stay or at least base my decisions on facts, and while not every designer might be right in every scenario, there are various studies which *are* a fact. You are right: Google makes mistakes, too, and they fix them (A prominent example in the Material design guideline are input fields, which formerly were only a bottom line and now are more common inputs with border and background again).

> Data shows 20% display energy saving [...] that's about 3.5 percent

Mixing in all facts would also require to adjust your calculation: While your linked article reduced the luminescence by `> 19%`, we can lower our luminescence at highest by `7%`, and this does not affect other UI elements like the branding in the navigation header and so on. Also you will have to multiply the result not with your screen-on time, but with the time you have the screen on *and* the Notes app in the foreground (minus the time when you are watching your homescreen, use other apps or pull down the notification panel, ...). And when it comes to an accuracy of this level, then yes - then i rely on my feelings and doubts, because this is also only the half of the truth. :wink: 

But: I don't deny the fact, that a little battery consumption will reduce the energy efficiency for AMOLED displays. It is just one argument that the benefits aren't as high as they might be expected. The bigger issue is the second half of my answer: The maintenance efforts simply aren't justified as long as Android does not provide support for a third mode beside `day` and `night` natively.

> Thanks for the reply I appreciate your sunday-afternoon efforts!

Happy to hear that!

> I will not request it again.

Even if i deny this particular feature request, i always appreciate feedback and also feature requests. It is important to reevaluate decisions which have been made from time to time and see if they are still valid. This project is used actively by more than 10.000 people and i rely on feedback and hearing a voice from my users. So please don't feel offended by this decision, but keep on contributing with ideas, bug reports and maybe a bit code in the future? :slightly_smiling_face:

**Comment by Samonitari** [comment]
> Mixing in all facts would also require to adjust your calculation: While your linked article reduced the luminescence by `> 19%`, we can lower our luminescence at highest by `7%`, and this does not affect other UI elements like the branding in the navigation header and so on.

I did a ballpark estimation. I could do better based on indivudual pixels' concumption for more accurate results, that was the first relevant piece of info found.
But: in the article some methods only reduced the luminence of non-ROI parts of the image and on still got 26% less energy consumption nevertheless, so we don't need to take "other UI elements like the branding in the navigation header" into account, as far as I think, that's covered.
I even lowered the article's average 22.5% (200 images, varying ROI size) saving, because I estimate gains pessimistically.

Also I mentioned that "You could argue your app is not eating any significant part on most phones and you are right."
I meant that - although badly worded - that you app is only a part of the daily/100% (nowdays the same :sad) screen usage.

But a mostly `UI-guidleline compliant` Android vs with mostly `gate to hell` Android can have at least a few percent difference.

I don't code for Android or in Java, so I had the wrong assumption.
I though you rewrite some values in the dark/night stylsheet/theme/whatever-delarative-file based on a toggle, and that's it,
My bad.

It was a good discussion, thank you for your attitude and continued efforts
