### ISSUE TITLE
Add undo(ctrl+z) option in the app while taking notes 

### ISSUE THREAD

**Issue by OpenWick** [stefan-niedermann/nextcloud-notes#1102]
While taking notes on android some times when u clear u accidentally delete more than necessary and since there is no undo option it is really a big problem as there is no way to reacquire the lost data

I consider it more of bug cause it is definitly essential for a note taking app. so please implement this feature so that crucial data may not be lost by sudden deletion.

**Comment by stefan-niedermann** [comment]
This is the repository of the Notes **Android** app. We do not develop the Web UI which you apparently refer to.

There is already a issue in the repository of the Web UI which sounds similar to your report: https://github.com/nextcloud/notes/issues/308
I recommend to upvote it using :+1: [GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) and subscribe to it to get notified when something new happens.

Last but not least: Please use the issue templates in the future instead of ignoring them, they are there for [a reason](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#why-has-my-bug-report-been-closed) (this is independent of Notes or even Nextcloud - all developers will be grateful for provided information) :wink:

**Comment by OpenWick** [comment]
Actually I am asking about Android App only. Is there an option for undo in the android app?

**Comment by stefan-niedermann** [comment]
Ah, now i understand you. The mentioning of the keyboard combination on an Android device confused me, but i see you meant "*like* ctrl+z".

We do not really have such a feature yet, this is correct. The closes thing is the "Cancel" in the three dots menu to restore the state of the note when it was opened.

However i don't think that such a feature will come soon to be honest - it is just incredibly complex work (recognize when one stopped typing, recognize words and sentences, state management backward and forward) and it is out of scope therefore at the moment.

**Comment by stefan-niedermann** [comment]
If someone is willing to implement **and maintain** it, i will of course accept this 😉
