### ISSUE TITLE
#tag-specified streams of notes

### ISSUE THREAD

**Issue by eMPee584** [stefan-niedermann/nextcloud-notes#1109]
I'm using the telegam 'saved message' stream a lot to put random notes or content fragments down for archival,  but I'd much rather use nextcloud notes for this.
it would be nice to have virtual streams specified simply by putting #tags in a note, and have multiple distinct date properties to filter on ( created, last modified, due, last state change) ...
and possibly having the streams available as share targets..

**Comment by stefan-niedermann** [comment]
The Notes app does currently support categorization but no tagging for various reasons.
Notes Android will follow the decisions of the server app (which is developed by an independent team) regarding this topic.

A corresponding issue exists in their repository and a pretty similar approach as you described has already been suggested there: https://github.com/nextcloud/notes/issues/299#issuecomment-752432115

Depending on what's happening in the server app, the Android app will follow, so i suggest you to upvote the linked comment 🙂.

As soon as a final decision has been made we will think about how the solution will be adapted to Notes Android for feature parity.

---

> it would be nice to have virtual streams specified simply by putting #tags in a note, and have multiple distinct date properties to filter on ( created, last modified, due, last state change) ...

Even though there isn't any special highlighting or else support, you can of course simply use hashtags in your notes and use the search function to filter your notes list by a specific hashtag. You can sort the result by last modified and alphabetically. Since Notes doesn't support due or states (and probably never will) most of the requested features are already possible anyway.
