### ISSUE TITLE
Enable code minification

### ISSUE THREAD

**Issue by connyduck** [stefan-niedermann/nextcloud-notes#1119]
I noticed this project has [code minification turned off](https://github.com/stefan-niedermann/nextcloud-notes/blob/e7ec28fe3c1116cff4690f85ac109c3088075773/app/build.gradle#L33). I would like to see it turned on because it looks like the savings in app size could be significant. If you want I can send a pull request.

**Comment by stefan-niedermann** [comment]
Nice finding, i just removed it to test it and the file size is (exactly) the same, though... any idea? Have you tried it?

**Comment by stefan-niedermann** [comment]
I was wrong, the size is indeed smaller :slightly_smiling_face:

**Comment by stefan-niedermann** [comment]
YJust wanted to let you know that i remember the reason and that we will disable the minification again 😆 

The reason is that we no longer are able to get meaningful stacktraces, so deciding whether we want a smaller app bundle or more information when a crash happens....

sampe:

```
b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.i.a(Unknown Source:124)
	at it.niedermann.owncloud.notes.main.MainActivity.C0(Unknown Source:71)
	at it.niedermann.owncloud.notes.main.MainActivity.D0(Unknown Source:0)
	at it.niedermann.owncloud.notes.main.l.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)
```

In case you know how to keep the full class and method names but still generate a smaller bundle size, a PR will be nice 🙂

**Comment by falzonv** [comment]
Hello Stefan,

I may have a solution for this one!

For my launcher application, I am minifying only the Android libraries and all my own classes and method are kept as-is.
This can be done in <code>proguard-rules.pro</code> by telling that everything under *the.package.name.\** should be kept ([example with mine](https://github.com/falzonv/discreet-launcher/blob/main/app/proguard-rules.pro)).

For Nextcloud Notes, it should be something like this to add in your <code>proguard-rules.pro</code> file:

```
# Shrink and obfuscate only Android libraries
-keep class it.niedermann.owncloud.notes.*
{
    <fields> ;
    <init>() ;
    <methods> ;
}
```

Note: this may not fit if you also want internal Android names in the stacktraces, or at least it will require additional rules in the file.

*My application being quite simple, I did not implemented anything to collect stacktraces so the use case is a bit different (wanting to reduce the app size, I read that minification can sometimes break things, and since the biggest elements were Android internal libraries I didn't want to bother with potential issues and reduced everything except my own classes).*

Best regards.

**Comment by stefan-niedermann** [comment]
That's interesting, though there appeared an exception which might be cause by the usage if the Nextcloud Single-Sign-On.

With your method we could at least analyze the cause.

Are you willing to make a PR to check this out? 🙂

**Comment by falzonv** [comment]
Hello,

I see that Konrad already created the PR, this is better since he seems to know more than me about ProGuard (I was not aware of, or had forgotten, the options <code>-dontobfuscate</code> and <code>-keepattributes SourceFile,LineNumberTable</code>).

Happy that the <code>-keep class</code> was useful for the Nextcloud SSO part :-)

Best regards.

**Comment by stefan-niedermann** [comment]
Sorry, i consider the risc being too high (at least with the current resources for this project). Something slipping through will be quite dangerous and recognized too late by me.

I really appreciate the effort you put into this and i would like to invite you to join #1036 which will be capable of reducing the final app size, too (by removing a complete dependency), but the minification topic is currently out of my scope.

Thank you & regards
