### ISSUE TITLE
Cant downgrade from 3.3.0

### ISSUE THREAD

**Issue by rogercreagh** [stefan-niedermann/nextcloud-notes#1139]
v3.3.0 is broken - ok so this might be fixed in 3.3.1 but that's not available yet.

In https://github.com/stefan-niedermann/nextcloud-notes/issues/1128 we are told that the workaround is to downgrade to a previous version - unfortunately attempting to downgrade to 3.2.5 (the previous version) on Fdroid says "Error installing Nextcloud Notes. Failed to install due to an unknown error"
Oh sh*t!
What now? Can't upgrade, can't downgrade, can't sync. :-(

**Comment by stefan-niedermann** [comment]
Just uninstall the app and the install the older version

**Comment by IngoBelka** [comment]
Deinstall 3.3.0 and install 3.2.5 is running well.

**Comment by stefan-niedermann** [comment]
@rogercreagh can you confirm that this is working, for you, too?

**Comment by rogercreagh** [comment]
Up to a point - stupidly I didn't realise that uninstalling would delete all the notes including today's unsynchronised ones, I assumed it would uninstall the app, not the data, or at least not without warning me.
So I've lost all today's notes - not a lot but including some data recording that I can't exactly remember the numbers for.

A note to anyone else going down this route - make a copy of anything unsyn'd before you uninstall.

**Comment by stefan-niedermann** [comment]
Unfortunately it's not possible to intercept the uninstall process (to warn a user) - everything else would be a security risc and it's therefore prevented by Android.

> I assumed it would uninstall the app, not the data

Well, have you ever uninstalled an application and the data stayed? I am afraid, that's not how it works.

Unsynchronized data on a smartphone is always a calculated risc of the user. By default settings, the notes are synchronized to the server after editing and going back to the list view. You can additionally set fixed background sync intervals in the settings.

I am happy to hear, that the installation of the older version works for you so far.

I am very sorry for the inconveniences and it's my bad that the defect version ended up on F-Droid. We are all human, and we all make mistakes after all.

**Comment by rogercreagh** [comment]
Well, have you ever uninstalled an application and the data stayed? I am afraid, that's not how it works.

- in my real world that is exactly how it works. Either the data stays or I get warned. Linux, MacOS, Windows all work like that But perhaps android is a world of its own and does things differently for "security" mad reasons.
Not your fault, my mistake for expecting a phone to act like every other device.

Come to think of it I'm pretty sure I have uninstalled phone apps before and the data has stayed - eg music players spring to mind, but maybe that's different. Anyway Notes is working correctly now with 3.2.5, thank you. I guess I'll stick with that version.

**Comment by stefan-niedermann** [comment]
> Anyway Notes is working correctly now with 3.2.5, thank you. I guess I'll stick with that version.

`3.3.1` is available on F-Droid and as i said the bug isn't there anymore.

> in my real world that is exactly how it works. Either the data stays or I get warned. Linux, MacOS, Windows all work like that But perhaps android is a world of its own and does things differently for "security" mad reasons.

While a music player and a gallery use shared files, they will of course also lose *their* information like favorites, pläylists etc as long as they aren't synced anywhere.

Just like Whatsapp, Telegram, Nextcloud and GMail will lose the data after uninstalling and only get them back after synchronizing, Notes does this, too. You can easily try that with the named apps. And this also happens of course with Thunderbird, Firefox, Chrome and so on on Desktops. Heck, even a office suite will lose the configuration. The files are of course saved outside, while the Notes app stores the notes inside the appss database for performance reasons.

Spoken purely technically a downgrade *is* possible but no app which i am aware makes use of this. Because it is simply not needed in case everything works as intend. And if something is broken, then the downgrade will have to be tested and will have to work. Usually messing around with the database again introduces only new problems.
