### ISSUE TITLE
after the update, notes won't connect to my nextcloud account

### ISSUE THREAD

**Issue by dtormanen** [stefan-niedermann/nextcloud-notes#1142]
When notes opens up for the first time, it asks to choose an account. I choose my nextcloud account and then notes says it cany connect. Notes has been working great until the last update. My other nextcloud apps connect and sync just fine. 

If I can make a suggestion for design principles, I say keep it simple. Less is more. I use to use Microsoft Note. In the beginning it worked OK. The more they so called tried to make improvements, the more it became so bloated it became a joke to use. Microsoft Note was always getting lost when trying to sync.

Less is more. Keep it simple. Awhile back Nextcloud Notes began automatically adding a #2 in the next line after I just finished making a note that began with  something like "1-1/2" PVC coupling". When hitting enter to go to the next line, Nextcloud Notes automatically adds a #2. That's incredibly anni. It's a disservice. I always have to and delete the added number 2. It's similar to spending more time correcting Apple or Googles autocorrect service than the amount of time the service saves. It's a waste of time and effort. You'll only be able to correctly anticipate a robots next action. People aren't robots. Most of them don't live in perfectly organized programmers world. Remember this. Less is more. Keep it simple.

Thank you for the great app you've created. It's been simple and perfectly functional in the past.
`
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.9.206-perf+(eng.root.20210330.153409)
OS API Level: 29
Device: river
Manufacturer: motorola
Model (and Product): moto g(7) (river)

---

b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.i.a(Unknown Source:124)
	at it.niedermann.owncloud.notes.main.MainActivity.C0(Unknown Source:71)
	at it.niedermann.owncloud.notes.main.MainActivity.D0(Unknown Source:0)
	at it.niedermann.owncloud.notes.main.l.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)

```


es for submitting issues:

* Bug reports which do not fill the complete issue template will be closed.
* Please have a look at our [FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md)
* Please search the existing issues first, it's likely that your issue was already reported or even fixed.
* This repository is *only* for issues within the Nextcloud Notes Android app
-->
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
<!-- A clear and concise description of what the bug is. -->


**To Reproduce**
Steps to reproduce the behavior:
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. See error


**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->


**Screenshots**
<!-- If applicable, add screenshots to help explain your problem. -->


**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 
 - F-Droid or Play Store: 
 - Android-Version: 
 - Device: 


**Server**
 - Nextcloud version: 
 - Nextcloud Notes version (server app): 

**Stacktrace**

**Comment by stefan-niedermann** [comment]
> Less is more. Keep it simple.

That's our motto :wink:

> Notes began automatically adding a #2 in the next line after I just finished making a note that began with something like "1-1/2" PVC coupling". When hitting enter to go to the next line, Nextcloud Notes automatically adds a #2.

- It is true, that we have an autocontinuation for lists (meaning `1. Item` will create `2. ` in the next line when pressing enter
- Don't overthink it, just hit <kbd>Enter</kbd> again and the `2. ` will go away - like in probably each other comparative app. Even Microsoft Word does it this way. Because this is, what the human users expect.
- In by far most cases `2. `  will follow to `1. Item`, so it makes perfectly sense to add it by default. This has absolutely nothing to do with "Robot thinking", it is easy statistics. We will keep it therefore because, you know, human users **expect** a list to be continued. Because it is a list. :wink: Otherwise: Why does no normal user use the Windows Notepad? The notes app exists for a bunch of years now, people come, people post their input like here, or at the Play Store ratings, i get even E-Mails. I think i have a feeling about how often which kind of feature got requested and what the expectations are. Automatically continuing lists is definitely an expected behavior. (Look what happens when it does not automatically continue, for example because of a bug: #316, #608, #937, #1039, #1040, #1050 to name a few)
- It is simply **not true** for the given sample content (i just tested it). If this auto continuation happens on a non-list as you suggested, open a proper [bug report](https://github.com/stefan-niedermann/nextcloud-notes/issues/new?assignees=&labels=bug&template=bug_report.md), so we can fix this behavior

Let me make some suggestions for communicating with "perfectly organized programmers", too - no offense, just take note for the future:

1. Read the issue template, don't ignore it
  - It is [there for a reason](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#why-has-my-bug-report-been-closed).
  - It would have told you to use the :mag: search function and find the [reasons and workaround for the crash](https://github.com/stefan-niedermann/nextcloud-notes/issues/1128)
  - Ignoring it is a sign of disrespect. It might be surprising, but "we" are also human. This is *my* free time and i will happily provide support as good as i can. Even for free users, but i expect a minimum of cooperation.
2. Design suggestions and contributions are welcome, and i am also a big fan of easy and simple apps. Please open separate issues in the future for concrete suggestions, so we can talk about them without mixing up various topics.

**Comment by dtormanen** [comment]
How can you close a ticket when you didn't do anything. It still doesn't connect to my nextcloud account.

```
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.9.206-perf+(eng.root.20210330.153409)
OS API Level: 29
Device: river
Manufacturer: motorola
Model (and Product): moto g(7) (river)

---

b.b.a.a.e.n: b.b.a.a.c.c
  at b.b.a.a.d.c.i(Unknown Source:33)
  at b.b.a.a.d.e.c(Unknown Source:6)
  at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
  at it.niedermann.owncloud.notes.persistence.i.a(Unknown Source:124)
  at it.niedermann.owncloud.notes.main.MainActivity.C0(Unknown Source:71)
  at it.niedermann.owncloud.notes.main.MainActivity.D0(Unknown Source:0)
  at it.niedermann.owncloud.notes.main.l.run(Unknown Source:4)
  at java.lang.Thread.run(Thread.java:919)

```

Apr 13, 2021 12:37:43 PM Niedermann IT-Dienstleistungen ***@***.***>:

**Comment by stefan-niedermann** [comment]
How can you comment when you didn't even read the response? https://github.com/stefan-niedermann/nextcloud-notes/issues/1128#issuecomment-817526516

**Comment by dtormanen** [comment]
OK. I see. Thank you.

Who knows what closed 1142 means? Let me offer you a suggestion on how to effectively communicate with people. Maybe say something like " The issue is resolved. Please see 1142. The update is being pushed ASAP".


Apr 13, 2021 12:55:39 PM Niedermann IT-Dienstleistungen ***@***.***>:
