### ISSUE TITLE
"Help: format" option in the menu

### ISSUE THREAD

**Issue by moshpirit** [stefan-niedermann/nextcloud-notes#116]
You could also add it to the About menu, for newbies that's a nice way to learn how to use it and why is he viewing his notes this way.

**Comment by dan0xii** [comment]
Would you explain what you'd like: A help menu that shows the user how to use the markdown formatting in the app?

**Comment by stefan-niedermann** [comment]
I think he means an menu point with a sample md document that explains how to use markdown.  At least this is my interpretation :)

**Comment by moshpirit** [comment]
I think I meant that too haha

**Comment by stefan-niedermann** [comment]
The server app displays an overview about markdown when no note is present yet. (@korelstar)

I personally do not like and will not follow this approach because:

- it is only accessible when no note is there
- it kind of "blows up" the empty content view

---

### Similar approach

@jancborchardt what do you think, which place would be accurate for such a help document:

- three-dot-menu in edit view
- in the sidebar above the "settings" entry
- as a new tab in the "about" view

**Pros**: Always accessible
**Cons**: Content might be different from server. It also creates a new menu entry anywhere which is always visible, even if the user isn't interrested in.

### Alternatively approach

When installing the server side app a new note could automatically be created which contains the markdown description.

This first "dummy" note then would be synchronized to the clients on startup where a user can keep or delete it.

**Pros**: Content is identical with server and one can keep or delete it
**Cons**: When one deletes it, it's gone forever.

**Comment by korelstar** [comment]
I don't like the dummy note approach. I think there should be a separate action to show such a help somewhere.

**Comment by stefan-niedermann** [comment]
Okay, then the remaining question is where to put the **help for formatting** notes with **markdown**:

- The ![grafik](https://user-images.githubusercontent.com/4741199/83966985-05a25a00-a8be-11ea-815a-0afe5c8de6e1.png) menu in edit view
- in the sidebar above the "settings" entry
- as a new tab in the "about" view

**Comment by jancborchardt** [comment]
> in the sidebar above the "settings" entry

I’d say this makes most sense. That way it’s reasonably accessible but not always in your face, especially for people who already know Markdown or don’t even use it. :)
We can simply call the entry "Formatting" and the content can be very similar to https://guides.github.com/features/mastering-markdown/ (the simplest and best Markdown guide for newcomers I found so far).

**Comment by stefan-niedermann** [comment]
Current progress: Merged into master, but disabled with a feature toggle.

We have to [clarify how to translate this stuff first](https://github.com/nextcloud/docker-ci/issues/199). Then i will enable this feature.

**Comment by stefan-niedermann** [comment]
Will be fixed in `2.14.0`. Sneak preview:

![a](https://user-images.githubusercontent.com/4741199/84073886-ec8acd80-a9d1-11ea-9fa1-c8ba37331624.gif)

# Current content:

---

# Context based formatting

A major design goal of the Notes app is to provide a distraction free tool. Though you will be able to format your texts with Markdown. For various of the below mentioned examples, you can use shortcuts so you can format your notes without typing in the codes below.
Just select a range of text or tap on your cursor at any position and you will get a popup menu which contains next to the default entries `Cut`, `Copy`, `Select all` entries like `Link` or `Checkbox`.

---

# Text

It's very easy to make some words **bold** and other words *italic* with Markdown. You can ~~strike~~ some words through and even [link to Google](http://google.com).

```
It's very easy to make some words **bold** and other words *italic* with Markdown. You can ~~strike~~ some words through and even [link to Google](http://google.com).
```

---

# Lists

Sometimes you want numbered lists:

1. One
2. Two
3. Three

Sometimes you want bullet points:

* Start a line with a star
* Profit!

Alternatively,

- Dashes work just as well
- And if you have sub points, put two spaces before the dash or star:
  - Like this
  - And this

```
Sometimes you want numbered lists:

1. One
2. Two
3. Three

Sometimes you want bullet points:

* Start a line with a star
* Profit!

Alternatively,

- Dashes work just as well
- And if you have sub points, put two spaces before the dash or star:
  - Like this
  - And this
```

---

# Checkbox

To create a checkbox, use a list followed by brackets

- [ ] Item 1
* [ ] Item 2

```
To create a checkbox, use a list followed by brackets

- [ ] Item 1
* [ ] Item 2
```

---

# Structured documents

Sometimes it's useful to have different levels of headings to structure your documents. Start lines with a `#` to create headings. Multiple `##` in a row denote smaller heading sizes.

### This is a third-tier heading

You can use one `#` all the way up to `######` six for different heading sizes.

If you'd like to quote someone, use the > character before the line:

> Coffee. The finest organic suspension ever devised... I beat the Borg with it.
> - Captain Janeway

```
# Structured documents

Sometimes it's useful to have different levels of headings to structure your documents. Start lines with a `#` to create headings. Multiple `##` in a row denote smaller heading sizes.

### This is a third-tier heading

You can use one `#` all the way up to `######` six for different heading sizes.

If you'd like to quote someone, use the > character before the line:

> Coffee. The finest organic suspension ever devised... I beat the Borg with it.
> - Captain Janeway
```

---

# Code

There are many different ways to style code with Markdown. If you have inline code blocks, wrap them in backticks:

\`var example = true\`
`var example = true`

Markdown also supports something called code fencing, which allows for multiple lines without indentation:

\`\`\`
if (isAwesome){
  return true
}
\`\`\`

```
if (isAwesome){
  return true
}
```

And if you'd like to use syntax highlighting, include the language:

\`\`\`javascript
if (isAwesome){
  return true
}
\`\`\`

```javascript
if (isAwesome){
  return true
}
```

---

# Unsupported

While we try to continuously improve the support for Markdown, there are a few features which are not yet supported by Notes:

- Tables
- Images

If you are interested in contributing support for one of those features, get in contact with us via GitHub or E-Mail.

**Comment by jancborchardt** [comment]
Good stuff! :) I'd only change 2 things:

- For simplicity, only mention the dashes for lists. Stars are for bolding, makes it easier to remember and dashes for lists also look better in plain text.
- The link to Google could instead be nextcloud.com? ;)

**Comment by stefan-niedermann** [comment]
> The link to Google could instead be nextcloud.com?

It *does* 😆 I thought the exact same, and the app *does* point to nextcloud.com^^

> For simplicity, only mention the dashes for lists. Stars are for bolding, makes it easier to remember and dashes for lists also look better in plain text.

I will adjust that in one of the next releases. I orientated at your link (GitHub flavored  Markdown).
