### ISSUE TITLE
Fix the bug for the function togglePunctuation() in MarkdownUtil

### ISSUE THREAD

**Issue by Cui-Yusong** [stefan-niedermann/nextcloud-notes#1193]
The togglePunctuation() function has some problems when during with special cases.
For example, this function can not distinguish * from ** ,and this should be fixed.

**Comment by Jimmy-7664** [comment]
I 'm a team member of  @Cui-Yusong .And I'm working on this issue.I wondering can we judging delete(eg. "Lorem *ipsum* dolor sit amet." and punctuation is"*", then delete to get "Lorem ipsum dolor sit amet.") or insert(eg. "Lorem **ipsum** dolor sit amet." and punctuation is"*", then insert to get "Lorem ***ipsum*** dolor sit amet.") only by the character in the original sentence and always return the new cursor position at the final position we made change? Here I'm a liitle confused about the input "selectionStart" and "selectionEnd"

**Comment by Jimmy-7664** [comment]
I 'm a team member of  @Cui-Yusong .And I'm working on this issue.
I wondering can we judging delete
(eg. "Lorem *ipsum* dolor sit amet." and punctuation is"*", then delete to get "Lorem ipsum dolor sit amet.") 
or insert
(eg. "Lorem **ipsum** dolor sit amet." and punctuation is"*", then insert to get "Lorem ***ipsum*** dolor sit amet.") 
only by the character in the original sentence and always return the new cursor position at the final position we made change? 
eg. We do delete because the original sentence only contains "*" but not contains "**".
eg. We do insert because the original sentence contains "*" and "**" but not contains "***".
Is this way working?Or we have to judge if it is surrounded by the punctuation?
Looking forward to your help.
Thanks a lot

**Comment by Jimmy-7664** [comment]
I 'm a team member of @Cui-Yusong .And I'm working on this issue.
I wondering can we judging delete
(eg. "Lorem \*ipsum\* dolor sit amet." and punctuation is"\*", then delete to get "Lorem ipsum dolor sit amet.")
or insert
(eg. "Lorem \*\*ipsum\*\* dolor sit amet." and punctuation is"\*", then insert to get "Lorem \*\*\*ipsum\*\*\* dolor sit amet.")
only by the character in the original sentence and always return the new cursor position at the final position we made change?
eg. We do delete because the original sentence only contains "\*" but not contains "\*\*".
eg. We do insert because the original sentence contains "" and "\*" but not contains "\*\*\*".
Is this way working?Or we have to judge if it is surrounded by the punctuation?
Looking forward to your help.
Thanks a lot

**Comment by stefan-niedermann** [comment]
- "Lorem *ipsum* dolor sit amet." and punctuation is"*", then delete to get "Lorem ipsum dolor sit amet." ✅
- "Lorem **ipsum** dolor sit amet." and punctuation is"*", then insert to get "Lorem ***ipsum*** dolor sit amet." ✅

Exactly, i think you got the point.
`**` means `bold`, if we toggle `*` (= `italic`), then we *add* `italic`, because it is not yet italic, but only bold.
`*` means `italic`, if we toggle `*` (= `italic`), then we *remove* `italic`, because it is already italic.
`***` means `italic AND bold`, if we toggle `*` (= `italic`), then we *remove* `italic`, because it is already italic, and the result is only `bold`
`***` means `italic AND bold`, if we toggle `**` (= `bold`), then we *remove* `bold`, because it is already bold, and the result is only `italic`

**Comment by Jimmy-7664** [comment]
Thanks a lot.
So Can I change the all return value(that is the new position of the cursor ) to the final position we made toggle change or to the original end if we don't make change?

**Comment by stefan-niedermann** [comment]
If i understand you correctly, then yes. Sorry for the lingual barrier, maybe just have a look at the available unit tests and propose your additions or changes to the tests in a PR, then we can discuss the expectations without misunderstanding 🙂

**Comment by Jimmy-7664** [comment]
Okkkk. I'll make a PR to show my idea ,then we can discuss it more.
