### ISSUE TITLE
Support Gemtext markup

### ISSUE THREAD

**Issue by ivanruvalcaba** [stefan-niedermann/nextcloud-notes#1195]
Is there a possibility to add support for Gemtext markup? Gemtext is a stripped down version of Markdown with very few variations (See: https://gemini.circumlunar.space/docs/gemtext.gmi).

Best regards.

**Comment by stefan-niedermann** [comment]
Thank you for your suggestion, but this is currently not on our roadmap for various reasons

- Our [base markdown editor](https://github.com/noties/Markwon/) which we rely on needs to support it first. I doubt that they will implement support for it since their goal is to implement support for the [commonmark](https://spec.commonmark.org/) specification.
- For feature parity the [Notes server app](github.com/nextcloud/notes/) will also need to support it, otherwise the feature set varies and this will only result in complaints
- We will lose consistency with the whole Nextcloud ecosystem which nearly entirely is based on Markdown, like [Nextcloud Text](https://github.com/nextcloud/text/) and [Nextcloud Deck](https://github.com/nextcloud/deck/)

I had a quick look at the linked quick introduction and i wasn't able to see any difference besides links via `=>` prefix. Since the Notes Android app automatically linkifies URLs in the preview mode, this is implicitly supported. This adds just another point to the list:

- Why should we commit to support another markdown/-up language with our limited resources for the long term, if it does not even bring any benefits?
