### ISSUE TITLE
Screen security is only for settings? And Cloud storage is unencrypted

### ISSUE THREAD

**Issue by pixincreate** [stefan-niedermann/nextcloud-notes#1232]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

One can bypass the security credentials to access the notes without using any brain!   
And as I observed, the Cloud sync is not at all encrypted but everything is just a plain text which can read by anyone!

**To Reproduce**
1. Turn on App Lock from settings of the app.
2. Open the app again. You'll be promoted with the device credentials.
3. Tap on the empty side
4. See, you just accessed the notes.
5. If you try to access the settings, it asks for credentials again and without entering the credentials you cannot enter into the settings.

**Expected behavior**

I should be restricted from using the app without unlocking e the option is toggled on. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.3
 - F-Droid or Play Store: F-Droid
 - Android-Version: 11
 - Device: Nokia 6.1 Plus LineageOS

**Server**
 - Nextcloud version: 3.16.0
 - Nextcloud Notes version (server app): mark.nl.tab.digital

**Stacktrace**
Doesn't exist for this.

**Comment by stefan-niedermann** [comment]
This is true, the server app currently does not support e2e encryption.

See the [last statement of the server apps maintainer](https://github.com/nextcloud/notes/issues/476#issuecomment-600482003).

**Comment by stefan-niedermann** [comment]
Regarding the device lock: It is labeled as `Beta` for a reason and has [known issues](https://github.com/stefan-niedermann/nextcloud-notes/issues/927). A contribution to enhance this situation will be very welcome 🙂

**Comment by pixincreate** [comment]
> Regarding the device lock: It is labeled as `Beta` for a reason and has [known issues](https://github.com/stefan-niedermann/nextcloud-notes/issues/927). A contribution to enhance this situation will be very welcome 🙂
> 
> By the way after unlocking the device, there is a threshold before it gets locked again after the last interaction. Tapping in the grey background is supposed to close the app.

I'd recommend adding an option for time-out or compulsorily ask credentials every time a user opens the app. And instead of closing the app on tapping the grey/empty region, you could show a notification asking to enter device credentials for upto 5 times? Then close the app.

**Comment by stefan-niedermann** [comment]
Asking for unlock on every interaction with the app makes it quite unusable. Asking for unlocking on every start up is
1. also pretty complex in the Android world due to the lifecycle of an app which is not simply "open" or "closed" but know various steps between like switching between the last two recent apps etc.
2. We had implemented it this way and got pretty much feedback from the beta channel from people who desired a small time främe before the app locks again

A further option will not be provided. This is one more thing which needs to be maintained and implemented and tested, and we simply do not have the resources for, neither will it improve the ux for the casual user to read and understand too many options. We aim to provide good default values instead of putting options for each and every edge case into the app.

Can you explain, why someone whose intention is to unlock the app, should tap 5 times in the grey backdrop? I don't see the use case here, but if you can explain this better and provide a Pull Request, i won't block it.

Look, I absolutely agree that the unlock-protection needs some more love and polishing. As soon as i have more time, i will try to solve the remaining issues. But please don't expect a vault which
- Allows you to enter custom PINs or protections
- Provides e2e encryption in the near future
    As stated in the server apps issue, this has not been implemented yet, has great error potential, needs huge maintenance efforts and there are already better alternatives. Use the Nextcloud app if you rely on this feature
- Encrypt the notes locally when the unlock protection is enabled
    The notes are living in a database within the app storage. This is separated by Android and protected from the access of other apps *except* one explicitly grants this access on a rooted device (and in this case the user should know what (s)he does or not root a phone at all)

**Comment by pixincreate** [comment]
Well I think you misunderstood my idealogy. Though you had valid points and made much sense,  
- I personally don't like when someone using my phone, open notes app either intentionally/unintentionally/curiosity etc., I write dumb things, my ideas to do, some senseless questions, quotes that I write when not in mood and etc.., and I really don't like someone snooping in it. I've seen kids in my family trying to snoop into my phone, trying to bypass the security and getting failed.  
- It's really good to have minimal options, as you above, and even don't support adding a custom pin in it either unless it is a password manager, which is not. Device credentials is far more than enough, with slight polish which closes the app notifying user with a toast asking to give the credentials inorder to access the notes.  
- But asking for credentials everytime you open the app is what I'd recommend. It's quite annoying when you've to enter device credentials like password/pattern/pin but not much when using fingerprint/face unlock options, right.? Correct me, if wrong, thanks. 🤗

**Comment by stefan-niedermann** [comment]
Relatable.

> I personally don't like when someone using my phone,

Just force close the app before giving the smartphone to other people, this will immediately lock the app again. 🙂 

> I've seen kids in my family trying to snoop into my phone, trying to bypass the security and getting failed.

I recommend to use Android profiles if multiple people are working with one device.

> But asking for credentials everytime you open the app is what I'd still recommend.

As i said, it's a trade-off between usability and security. And ultimately the users from the Beta channel made the decision, it was pretty clear that even with biometric sensors, it was considered as nerving. 🤷

**Comment by pixincreate** [comment]
> Just force close the app before giving the smartphone to other people, this will immediately lock the app again. 🙂

Special thanks for letting me know that. I'd thought I've to either reboot or just turn off the phone to lock the app.


> I recommend to use Android profiles if multiple people are working with one device.

Sure, thank you for the reply.
