### ISSUE TITLE
Logcat contains all notes in plaintext

### ISSUE THREAD

**Issue by dedors** [stefan-niedermann/nextcloud-notes#1243]
**Describe the bug**
I'm a noob in this topic, but I saw **all** my notes in plaintext in the android logcat when it does a sync job. Shouldn't something like that be hidden or encrypted? 

**To Reproduce**
Open logcat reader
Wait until it syncs.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.2
 - F-Droid or Play Store: F-Droid
 - Android-Version: 11
 - Device:  Xiaomi Mi Note 10 Pro LineageOS

**Server**
 - Nextcloud version: 21.0.2
 - Nextcloud Notes version (server app): 4.0.4

**Stacktrace**

**Comment by stefan-niedermann** [comment]
I don't consider this issue as critical because, as far as i know, reading logs of another app is not possible by default and requires the `android.permission.READ_LOGS` permission. This needs to be granted when installing an app and therefore belongs to the responsibility of the user.

Quoting from the Android [developer page](https://developer.android.com/reference/android/Manifest.permission#READ_LOGS):

> [...]  Log entries can contain the user's private information.

Though I agree that the content of the notes shouldn't be visible (also for performance reasons). It is necessary only for development.
I will build a switch to only log the content while debugging. 🙂

**Comment by stefan-niedermann** [comment]
All right, the **content** of the notes will no longer be visible in LogCat. I also removed some other information which might be sensitive (logs when toggling checkboxes, entered search terms, ...).

Those changes will be shipped with `v3.4.5` and only for production builds (Play Store, Play Store Beta channel, F-Droid and Huawei App-Gallery).

Please note, that this change does *not* affect meta information (*including* title and category) on purpose. As I told [above](https://github.com/stefan-niedermann/nextcloud-notes/issues/1243#issuecomment-851870751), logs are meant to be helpful in case something goes wrong and i think this is a good compromise between "A user grants `READ_LOGS` permission to an untrustworthy app" and the need to make valuable information accessible to the user in an error case.
