### ISSUE TITLE
Add formatting toolbar in editing mode

### ISSUE THREAD

**Issue by cdelledonne** [stefan-niedermann/nextcloud-notes#1252]
**Is your feature request related to a problem? Please describe.**

Hi, first of all: great app, thank you for putting effort in it. I've been using the app more and more lately, and I think I would find useful some kind of formatting toolbar to improve my workflow even more while editing a note. I don't think I have seen a similar feature request, apologies in advance if I have missed something.

**Describe the solution you'd like**

The formatting toolbar I have in mind would allow quick insertion of headers, links, lists and checklists when in edit mode.

**Describe alternatives you've considered**

I'm aware that most of these actions can be performed through the context menu that appears when pressing and holding in the note view. However, I would find quick action buttons a bit more intuitive and faster to use.

**Additional context**

Here's a mockup screenshot that depicts what I have in mind. The exact formatting actions and icons do not necessarily have to be these ones of course.

![nextcloud-notes-mockup-resized](https://user-images.githubusercontent.com/24732205/120933447-79a65680-c6fa-11eb-9491-f1336310f71b.png)

**Comment by stefan-niedermann** [comment]
Hi and thank you for the kind words!

There are various good reasons to do it, and also some to not do it, but in the end we have no plans to implement this at the moment.

Main goal is to provide a distraction free note taking app with minimal visual elements which deviate people from writing down the actual content. Options to apply markdown formatting are provided in a context as you have already discovered (therefore the "context based formatting"), but we explicitly aim to **not** be a word processor (aka "Word on a smartphone").

Besides those, let's call it "ideological" reasons, there would be a big bucket of technical issues which will make it quite hard to implement *and* maintain such a toolbar. The markdown editor is developed as an independent module and is also used in the [Deck Android](https://github.com/stefan-niedermann/nextcloud-deck/) app which makes it kind of hard to find one universal UI which fits for every context (for example a little comment field is not comparable with a description field).

I appreciate the feedback though and no decision is ever final. You have *not* been the first one who wrote this feature request, and you are most probably not the last one. I will reevaluate the decision from time to time and maybe i come to another conclusion in the future (especially since context based formatting doesn't work properly due to a bug in MIUI on Xiaomi devices). But for now as i said: We have currently no plans to implement this.

**Comment by ln-12** [comment]
@stefan-niedermann First of all, I would also say thank you for your awesome work! :) 

I totally agree with @cdelledonne that such a toolbar would be great, specially for users who are not familiar with markdown. What do you see as main issue when it comes to maintaining such a toolbar? And would you be open to contributions using Kotlin/Compose?

**Comment by dodekaphilist** [comment]
Just stumbled across this app and thought the functionality mentioned in the issue is absolutely necessary to make it really useful for a broader range of people (including myself :D)
@stefan-niedermann Any news on this topic, I see there is an offer for help in the comment above me..?
