### ISSUE TITLE
Cannot confirm connection to Nextcloud account

### ISSUE THREAD

**Issue by wzurborg** [stefan-niedermann/nextcloud-notes#1357]
I installed the app on a Samsung tablet with an existing Nextcloud account. On first start it finds the account and offers me to connect to it. But the popup does not have an Ok button, so I can't confirm it. I tried to work around it by specifying the existing account as a new one but ran into the error "Account already exists". So I am stuck right at the beginning.

**To Reproduce**
- Install the app on a device with an existing Nextcloud account
- Choose to connect to the existing account
- You cannot confirm the choice due to a missing Ok button

![grafik](https://user-images.githubusercontent.com/1320950/135077383-c42d6fc6-0fac-41c0-a135-83f9aa4fb958.png)

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version: 3.4.11
 - F-Droid
 - Android-Version: 10
 - Device: Samsung Galaxy Tab A

**Server**
 - Nextcloud version: 17.0.10
 - Nextcloud Notes version (server app): 3.6.4

**Comment by stefan-niedermann** [comment]
Please clear the storage of the Notes Android app as [described in the FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#tokenmismatchexception-and-all-others) to get rid of the corrupt database state.

Regarding the submit button - i guess it is there and just invisible due to theming issues. Since this dialog comes from the [Nextcloud Single Sign On library](https://github.com/nextcloud/Android-SingleSignOn/issues/new) or the ]Nextcloud files app](https://github.com/nextcloud/android/issues/new?assignees=&labels=bug&template=bug_report.md) (and not the Notes android app) I'd like to ask you to open issues in the linked repositories in case the issue persists.
