### ISSUE TITLE
Handwritten notes

### ISSUE THREAD

**Issue by lumbo7332** [stefan-niedermann/nextcloud-notes#1419]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to handwrite notes and draw diagrams/pictures with a stylus in the Nextcloud Notes app, and have them synced to my Nextcloud account.

**Describe the solution you'd like**

Implement handwriting of notes. They could possibly be saved as an embedded SVG in a Markdown file?

**Comment by stefan-niedermann** [comment]
Hi @lumbo7332 

since this feature has been requested multiple times, I added a [section in our FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#why-is-there-no-support-for-pens). Don't get me wrong, I'd love to implement this feature. Since there are some serious obstacles though, I can't see any progress at this point soon unfortunately.

Contributions are of course welcome!

Regards
