### ISSUE TITLE
Error: Exception bug when syncing notes

### ISSUE THREAD

**Issue by schmoops1** [stefan-niedermann/nextcloud-notes#1422]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Notes won't sync and note body text is replaced with "Error: Exception".

**To Reproduce**
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

**Expected behavior**

Expected notes to refresh and sync with Nextcloud.

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.16
 - F-Droid or Play Store: F-Droid
 - Android-Version: 11
 - Device: Google Pixel 

**Server**
 - Nextcloud version: 
 - Nextcloud Notes version (server app): 

**Stacktrace**

```
App Version: 3.4.16
App Version Code: 3004016
App Flavor: fdroid

Files App Version Code: 30180090

---

OS Version: 4.9.248-ab202112110(202112110)
OS API Level: 30
Device: bonito
Manufacturer: Google
Model (and Product): Pixel 3a XL (bonito)

---

java.lang.Exception: {"errorType":"Exception"}

	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:145)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by stefan-niedermann** [comment]
This looks like an exception coming from your Notes server app.

- Are you able to access and create your notes via browser?
- Can you see any related entries in your Nextcloud server log?

**Comment by schmoops1** [comment]
I forgot my password and I'm not getting a reset email.

**Comment by schmoops1** [comment]
I've logged in to my provider (Cloudamo) but there's no option to view my data. I tried logging in to the Nextcloud site and it said my login info is incorrect.

**Comment by stefan-niedermann** [comment]
Well, then this is something you should fix first :wink: 
The Notes Android app depends on a working Nextcloud instance (which is reachable via Browser), installed and configured Nextcloud Android app (for Files) and a installed Notes app on your server. This is also mentioned in the description, so please ensure that those prerequisites are fulfilled.

Please feel free to reopen this issue (or open a new one) if the Notes Android app still keeps failing then :slightly_smiling_face:.

**Comment by 0cwa** [comment]
This might be an issue with cloudamo, I've got the same error code trying to access the notes on the cloudamo website.

**Comment by Petermhen** [comment]
Were you able to solve this issue "error:exception" issue on Cloudamo's end? I'm getting the same error on all of my notes as well.

**Comment by 0cwa** [comment]
I'd just switch away off of cloudamo, they don't seem to be set up that well, I'd always get error notifications when syncing via Dav, I just ditch them.  Webo seems to be set up much better.

**Comment by Petermhen** [comment]
> I'd just switch away off of cloudamo, they don't seem to be set up that well, I'd always get error notifications when syncing via Dav, I just ditch them. Webo seems to be set up much better.

Agreed, I just need to get all of my notes off their servers. Hoping they didn't delete or irreparably corrupt them...

**Comment by Petermhen** [comment]
Cloudamo tech support finally replied & said that this issue is a bug in Nextcloud & that he filed a bug report for it. Don't have a link to the bug report as yet.

**Comment by Petermhen** [comment]
Shouldn't this app store a local offline copy of the notes, to have redundancy in case of situations like this? That's the whole point of syncing things to the "cloud".

**Comment by 0cwa** [comment]
> Cloudamo tech support finally replied & said that this issue is a bug in Nextcloud & that he filed a bug report for it. Don't have a link to the bug report yet.

I think that's the point of the Nextcloud app, if you want a local copy, then do that on there.  A setting to set new notes to save locally in the NC app might be useful though.  What do you think?

**Comment by 0cwa** [comment]
I think that's the point of the Nextcloud app, if you want a local copy, then do that on there.  A setting to set new notes to save locally in the NC app might be useful though.  What do you think?

Mar 29, 2022 2:05:13 PM Petermhen ***@***.***>:

**Comment by stefan-niedermann** [comment]
> Cloudamo tech support finally replied & said that this issue is a bug in Nextcloud

That's funny because 1. this exact issue has never been reported by an user on any other hoster and 2. Cloudamo themself told me that it was an issue by them.

![Cloudamo response](https://user-images.githubusercontent.com/4741199/160758915-bd343135-1318-4f56-9dd0-ab863e149696.png)

> I think that's the point of the Nextcloud app, if you want a local copy, then do that on there.  A setting to set new notes to save locally in the NC app might be useful though.

Sorry, but I do not understand your proposal. Which "Nextcloud app" do you mean? The Nextcloud Android app? The Notes Server app? Why should one want to "save new notes locally in the NC app" (I assume you mean the Nextcloud Android app by "NC app")? In which relation is this to the issue with Cloudamo?

**Comment by 0cwa** [comment]
I guess Petermhen deleted their comment?  I was responding to this comment:
>>Shouldn't this app store a local offline copy of the notes, to have redundancy in case of situations like this? That's the whole point of syncing things to the "cloud".

Yes, I was refering to The Nextcloud Android app.

**Comment by Petermhen** [comment]
> I guess Petermhen deleted their comment? I was responding to this comment:
> 
> > > Shouldn't this app store a local offline copy of the notes, to have redundancy in case of situations like this? That's the whole point of syncing things to the "cloud".
> 
> Yes, I was referring to The Nextcloud Android app.

Yes I deleted the comment, my bad. I deleted it because I remembered that the Nextcloud Notes Android app interfaces with the Nextcloud Android app and not directly with Nextcloud server, so the responsibility for storing a local copy of the notes on the Android phone would rest on the Nextcloud Android app. 

That said I agree with your proposal. If the Nextcloud Android app isn't saving a local copy of the notes then it'll be helpful if the Nextcloud Notes app could provide an option to change this setting in the Nextcloud Android app, or show a notification to inform the user of this issue. That's given that there's a way for the Notes app to tell if a local copy is being saved or not.

**Comment by Petermhen** [comment]
> > Cloudamo tech support finally replied & said that this issue is a bug in Nextcloud
> 
> That's funny because 1. this exact issue has never been reported by an user on any other hoster and 2. Cloudamo themself told me that it was an issue by them.
> 
> ![Cloudamo response](https://user-images.githubusercontent.com/4741199/160758915-bd343135-1318-4f56-9dd0-ab863e149696.png)
> 
> > I think that's the point of the Nextcloud app, if you want a local copy, then do that on there.  A setting to set new notes to save locally in the NC app might be useful though.
> 
> Sorry, but I do not understand your proposal. Which "Nextcloud app" do you mean? The Nextcloud Android app? The Notes Server app? Why should one want to "save new notes locally in the NC app" (I assume you mean the Nextcloud Android app by "NC app")? In which relation is this to the issue with Cloudamo?

It would seem like Cloudamo is just looking to avoid having to do the work to solve the issue. Turns out that it's not just the notes that are inaccessible (which I just realised are stored in a "Notes" folder in Nextcloud Files), but all Nextcloud files are inaccessible on Cloudamo's server & throwing this error:
`Internal Server Error
The server was unable to complete your request.
If this happens again, please send the technical details below to the server administrator.
More details can be found in the server log.

Technical details

    Remote Address: 172.70.130.96
    Request ID: YkOEFzaVNB4fS4fjjP3JFAADwRE
`
They've told me once again that it's a Nextcloud bug but can't produce a link to the supposed bug report that they filed. Cloudamo also can't assist with migrating my data to another Nextcloud installation (even on their servers), can't provide me a dump of the database or any assistance so apparently all of my notes are gone.

It was a mistake having anything to do with Cloudamo. Just leaving these details here for anyone else who may be facing this error or considering having any dealings with this company.

**Comment by 0cwa** [comment]
> Cloudamo also can't assist with migrating my data to another Nextcloud installation (even on their servers), can't provide me a dump of the database or any assistance so apparently I can never get my notes back.

Damn, that's rough, I'm sorry to hear that.  I was at least able to pull my notes off the server still after getting that error, I hope you might be able to later
