### ISSUE TITLE
Can't select Account at startup

### ISSUE THREAD

**Issue by HerrGuhr** [stefan-niedermann/nextcloud-notes#1502]
Hi!
After fresh install I can't select a account. 
The Popup immediately disappears (but I can see its empty) 
I use nextcloud and have davx5 installed
Samsung S20 5g Ultra with actual updates

**Comment by stefan-niedermann** [comment]
Hi @HerrGuhr !

please fill out the complete issue template, it is there [for a reason](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#why-has-my-bug-report-been-closed).

- Which version of the Nextcloud Android app (**not** Notes Android!) do you have installed?
- Did you get the app from Play Store, F-Droid, AppGallery, Self-Built....?

> with actual updates

I am afraid that I don't know what the "actual update" is for each device and each manufacturer (shame on me). Would you mind posting at least the Android major version you are using?

**Comment by stefan-niedermann** [comment]
Closing due to missing feedback. Feel free to open a new issue [filling out the complete issue template](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#why-has-my-bug-report-been-closed) and answering [the questions](https://github.com/stefan-niedermann/nextcloud-notes/issues/1502#issuecomment-1100628524).
