### ISSUE TITLE
Support ToDo Checkboxes

### ISSUE THREAD

**Issue by Offerel** [stefan-niedermann/nextcloud-notes#157]
Hello, i think the Server doesn't support this at the Moment, but what i wish to have, is a CheckBox Feature for ToDo Lists. I mean the famous "Shopping-List" Feature like in Google Keep and other Systems. Nice to have feature.

**Comment by stefan-niedermann** [comment]
Well there will be checkboxes in v0.10.0 but they are not clickable.
Since i am not reinventing the wheel, i build the app on top of [RxMarkdown](https://github.com/yydcdut/RxMarkdown) (v0.10.0 and higher) - So i am limited to the features that this library has built in.
I will open a feature request once v0.10.0 has been released.

**Comment by stefan-niedermann** [comment]
RxMarkdown is tracking this feature for edit mode: https://github.com/yydcdut/RxMarkdown#editfactory

I am closing this issue because it is basically a feature that is needed to be implemented by RxMarkdown itself.

btw: @Offerel the new markdown lib is merged to master and will be released for F-Droid in a few days. Would be glad if you could update and test it :)
