### ISSUE TITLE
Support Categories

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#165]
Since the server is able to handle categories (v2.2.0), the android client should be able to deal with this, too.
- Extend database, DTOs, etc.
- Extend user interface: thought about a swipeable sidebar on the left side like the android news app

**Comment by korelstar** [comment]
Yes, but the categories on the server-side are quite rudimentary: you can't change them in the app (only if you move a note's file in a sub-directory) and they are not shown yet. Nevertheless, the API already delivers the information, but changes are not possible.

Therefore, currently we can only *show* the categories in this app. But of course, this would be nice :-)

Since I had to change the database for #154 and nextcloud/notes#49, I've already added the category attribute and show it in the main activity. Hence, your first point is already done. I will commit and push my changes later on, but they are interweaved with the prototype from nextcloud/notes#49, so this should stay in a separate branch until nextcloud/notes#49 is resolved.

However, a possibility to filter the task list by category is still missing. For this purpose, I would also propose to use a sidebar ([navigation drawer](https://material.io/guidelines/patterns/navigation-drawer.html)). We could integrate the menu from the ActionBar here, too:

- All notes (?)
- Starred/Favorites
- Uncategorized
- Category 1
- ...
- Category *n*
- *separator*
- Settings
- About

Some designers would have to think about the design for the upper area of the navigation drawer. Typically, a picture, avatar and/or the app icon is shown here.

**Comment by stefan-niedermann** [comment]
Yeah, this was more a note for me and [everyone who is waitin for this feature](https://play.google.com/store/apps/details?id=it.niedermann.owncloud.notes&reviewId=Z3A6QU9xcFRPSEJfSlFEQ3VmZUNBU3puTV9oOG9qa1NwWFZjRWFJUlVkbzFyazR3UlpPWTczb08zaHloR2FPSDJWaXJaT1pxa1RrVHlsMXNLOGlMVi1ORmc). I already noticed, that it is currently impossible to edit the categories via the webinterface.

Sure, if we introduce a sidebar, there should be entires for "All", "Favorites", and so on and it absolutely makes sense to move the settings there, too because the material design guidelines say that's the place where they belong 😆 

Also we can fetch the avatar (should be possible yet) and ideally we could display the wallpaper that is chosen on nextcloud instances (not sure if this is possible yet).

> so this should stay in a separate branch until nextcloud/notes#49 is resolved.

Yep, i will create one (RxMarkdown branch is merged to master, btw).

But: I am a friend of many little baby steps, so
1. introducing a sidebar with "All" and "Favorites" would be the first step.
2. move settings and about into the sidebar
3. show cateories (not editable)
4. (as soon as the server supports it): make categories editable

You and me have little time, but each of those steps is a benefit for the users, so lets split this down to some issues and do on after the other :)

**Comment by marco-bien** [comment]
+1 for your roadmap! Thanks.
