### ISSUE TITLE
Make workflow configurable NotesList -> EditNote -> PreviewNote

### ISSUE THREAD

**Issue by ThingsGetWorse** [stefan-niedermann/nextcloud-notes#217]
Hi,
in version 0.11.0 (or possibly earlier, I only got the new feature today via Google Play) PR #141 was merged. I would like to vote to make that flow configurable.

**Options**
    NotesList -> EditNote -> PreviewNote
    NotesList -> PreviewNote -> EditNote

I use the Notes app as an Evernote Replacement so I add notes, sure, but also scroll through and read them. So please make the behavior of the NotesList screen configurable.

**Comment by stefan-niedermann** [comment]
Hi, it is planned to merge EditNote and PreviewNote into one activity with a toggle-button to switch the views. the view will be stored, so of you reopen a note the state will be recovered. would this planned behavior match your request?

**Comment by ThingsGetWorse** [comment]
Hi, that feature sounds good but still requieres me to go through all notes switching state to 'PreviewNote', right?
So request would stay the same, let me chose which  view should be default. :-)

**Comment by stefan-niedermann** [comment]
It is not decided yet if the state will be per note or global - but we can include this to the decision finding :)

**Comment by ThingsGetWorse** [comment]
👍

**Comment by schaarsc** [comment]
I'd like to suggest a preference with three options:
- Always open notes in edit mode (default)
- Always open notes in preview mode
- remember my last decision (for each note???)

**Comment by minimeee** [comment]
I agree with @schaarsc. Just think about the following workflow:

I have some notes that act as "read-only lists" 90% of the time, but sometimes I add or modify something. After doing that, I close the note because I'm done. Next time I'd like to read it, as I'm used to. However, if the app stores the last state, I would immediately enter "edit mode" (which I don't want). In order to get into "view mode" next time I open a note, I'd have to remember to switch to it each time I've edited the note. That's inconvenient imho and not a replacement for a permanent option...

**Comment by korelstar** [comment]
@schaarsc has implemented this in #242 👍
