### ISSUE TITLE
Make the app more customizable

### ISSUE THREAD

**Issue by minteral** [stefan-niedermann/nextcloud-notes#219]
Would be nice to get some settings to customize the app.
I'd like to disable the swipe to delete function. 
And an option to disable the note content in the overview, to just see the note name.

Great app, by the way. Thanks a lot!

Version: v0.11.0

**Comment by stefan-niedermann** [comment]
Dear @minteral 
i can understand your request to customize the app more. Please note, that a major design goal of this is simplicity. Therefore i will add only and really **only** a setting if i can see a benefit for the majority of the user base.

> I'd like to disable the swipe to delete function.

Since @korelstar contributed the undo-functionality i will not implement a setting for this. Sorry.

> And an option to disable the note content in the overview, to just see the note name.

Can you explain me a concrete use-case for it? Why should one want to do this? And: Would be a password protection for the app be a solution for this issue?

> Great app, by the way. Thanks a lot!

Really happy to here that :) Thank you very much.

**Comment by minteral** [comment]
Dear @stefan-niedermann

> Please note, that a major design goal of this is simplicity. Therefore i will add only and really only a setting if i can see a benefit for the majority of the user base.

I completely understand and respect your decision for a simple app design. Just wanted to give some feedback about functions, that i think, could be useful.
Because it happened to me more than once, that i missed the opportunity to use the undo function and had to recover the deleted notes from a backup.

> And an option to disable the note content in the overview, to just see the note name.
>> Can you explain me a concrete use-case for it? Why should one want to do this? And: Would be a password protection for the app be a solution for this issue?

I thought it would be clearer, with just the "name" of the note in the overview.

But like i mentioned, this were only suggestions, i wanted to share.

Thank you for the detailed answer and your time

**Comment by korelstar** [comment]
Regarding the swipe-to-delete feature, please have a look at #207 and give feedback, there! (see also #225)

**Comment by stefan-niedermann** [comment]
While i think for both use-cases noboption is needed, have a look at #387 - swiping from left to right will be way less destructive in the future.

About only showing the title: I think it's just fine as it is, because in the first line often only headings are used, while it might ne hard to distinguish between notes with similar headings.

Thank youbfor your feedback anyway.
