### ISSUE TITLE
Improve note swipe->delete feature

### ISSUE THREAD

**Issue by KopfKrieg** [stefan-niedermann/nextcloud-notes#225]
I hope it's not just me, but often I try to click on a note (open it), and accidentally swipe just a little bit and the note gets deleted. I don't know if there a threshold value for the swipe operation, but maybe that could be set a little bit higher?

If not, maybe one (or both) of the following features could be implemeted:
 - Do not allow to delete a note through swipe if it's marked as favourite
 - Instead of just displaying something got removed show which note got removed

Thanks.

**Comment by korelstar** [comment]
I can understand you very well: sometimes, I have my problems with this feature, too. My latest approach in order to improve the situation is to let the phone vibrate on list item movement. I made a pull request for this: #207. Please test it and give feedback!

**Comment by KopfKrieg** [comment]
I installed Android Studio, imported the project and checked out the origin/vibrate branch, but my phone won't vibrate after installing the new apk on list item movement. Could you provide me an working apk to test this feature?

**Comment by korelstar** [comment]
Thanks for testing this! I have two questions:

1. Can you please have a look at the Android Monitor logcat output in Android Studio while having your phone connected and the app started on the phone from Android Studio? Is there a output "vibrate" (log level verbose) when beginning to swipe a list entry? This should be there, regardless of my next question. Otherwise I have to provide the APK file for you.

2. I found this regarding vibration: https://stackoverflow.com/questions/27994560/what-is-the-shortest-duration-vibrator-vibrate-can-be-called-with-where-the-de - so maybe, my vibration duration is too short. Can you please test another value (larger than 20, e.g. 50 or 100) in line 336 of NotesListViewActivity ( https://github.com/stefan-niedermann/nextcloud-notes/blob/feed4f92142403086481d1e9e08b94eb84ca6279/app/src/main/java/it/niedermann/owncloud/notes/android/activity/NotesListViewActivity.java#L336 ) ?

Thanks!

**Comment by KopfKrieg** [comment]
Thanks for your fast response. I tested a few configurations and the minimum vibration time needs to be 100ms on my phone (but then it's really just a short vibration). Maybe set the the time to at least 150ms?

Besides that, vibration works just fine as reminder that something got deleted.

**Comment by korelstar** [comment]
Thank you very much for testing and investigating. The minimum vibration duration really seems to be very varying for different devices. I adjusted the time to 100ms, since it should stay very short.

More tests with other devices are welcome! 😉

**Comment by KopfKrieg** [comment]
Thanks :)

**Comment by KopfKrieg** [comment]
Thanks :)
