### ISSUE TITLE
Introduce a trashbin

### ISSUE THREAD

**Issue by gardiol** [stefan-niedermann/nextcloud-notes#238]
Accidental delete by swipe is annoying. Yes it can be restored, but only from nextcloud file web app, and not from note app.

Please add the option to confirm swipe-delete 

This is specially needed by limited mobility or disabled people.

**Comment by schaarsc** [comment]
I suggest to rename this issue into "confirm delete" because delete from menu is also missing a confirmation.

Suggestion:
- create "confirm delete" dialog with "don't show this dialog again" option
- add dialog to swipe-to-delete and menu-delete
- add confirm-delete option to preferences (this is optional, but without the don't-show-again option cannot be changed)

**Comment by stefan-niedermann** [comment]
Well, i like and follow the opinion of @jancborchardt here: Undo is better than confirmation, because users are trained to simply "click away" every pop up.

So i think showing this dialog is wrong. We should better enhance swipe2delete to be less sensitive. Maybe displaying the Undo-action longer would be another point.

When we have a sidebar we could ask for extending the API to get trashbin-information so we can display a own trashbin where notes can be restored from.

**Comment by schaarsc** [comment]
for me proper trashbin/undo is an acceptable alternative to confirmation dialog. toast are (depending on the situation) either shown to long or to short.

**Comment by gardiol** [comment]
While in my opinion a "confirm dialog" is the only **accessible** solution, despite all the rage about material design and this (insert your adjective here) fashion... I understand that i cannot row against the masses. Nor i agree with the "let's dumb down UI because people clicks like crazy" idea... it's a make them all dumber instead of having them grow up approach which i find very damaging in the long run.

But i am not here to discuss or impose my views! so, indeed making the delay longer for the toast would help... while you implement a proper trashbin, which would be the actual solution in this case.

Or, what about a "confirmation" which is not a dialog but a button which is revealed after swiping? I am thinking at the notifications in Android 6+, where if you swipe on the persistent ones you reveal a button to access per-app notification settings. This would keep the swipe-to-delete and ensure no accidental deletions without an additional dialog? You could even remove the toast altogether!

**Comment by korelstar** [comment]
I like the idea of an integrated trash bin. Is there an API for that in nextcloud/server (REST or PHP?)

**Comment by stefan-niedermann** [comment]
yes i think there is a REST API, but it would list all deleted files, so the notes server app would have to provide an API that filters the entries for only deleted notes (i think this should be possible, detect if the deleted resource folder is the notes folder)

**Comment by jancborchardt** [comment]
Confirmation dialogs are simply bad design as people tend to click them away anyway. Undo is a much better and error- safe solution. @gardiol I recommend reading this article: https://alistapart.com/article/neveruseawarning

**Comment by jancborchardt** [comment]
And undo would still need to be there even with a trashbin. Going to the trashbin to recover a note is a workaround and cumbersome.

Also, it’s overengineering regarding the problem we have, which is simple accidental deletion.

**Comment by korelstar** [comment]
@jancborchardt 
I don't think a tashbin is that bad. The article you've linked indicates a trashbin as a good practice. In my view, a trashbin is an undo function which is accessible for a longer period of time. Hence, it would be a good solution for this app: We use the SnackBar for undo functionality, which is accessible for a very limited time-period, only (Android only provides two durations and we are using the longer one already). With the trashbin, we can extend the time-period in which the user can undo a delete without being annoying to user who really want to delete. That's great, isn't it?

Btw.: if you say, a trashbin is bad, why does Nextcloud have it at all?

**Comment by korelstar** [comment]
@jancborchardt 
We have an undo function for a long time. So what do you are talking about?

**Comment by jancborchardt** [comment]
@korelstar sorry, misworded: I think the current way is good with undo. Maybe it needs to be adjusted. If you like to implement a trashbin on top sure - but undo should work perfectly anyhow. :)

**Comment by gardiol** [comment]
@jancborchardt i well know the article you linked and i agree with the general principle, but THAT consideration does NOT take into account disabled people nor accidental AND unattended actions.

**@everybodyelse**, the undo in place indeed works, but i has never helped me when i needed it the most. Why? Well, when it happens it's because i am either not looking at the phone (never accidentally unlocked your phone in the pocket or while holding it but not looking?) or i am holding it in a very awkward position (never being using it while in bed holding a kid who is just fallen asleep in your arms?) and reaching for the undo cannot be achieved. 

So yes, please, a trashbin would be very nice!

**Comment by jancborchardt** [comment]
Alright, then trashbin it is. :) If it's nicely integrated with the server trashbin that's good.

**Comment by stefan-niedermann** [comment]
Okay, to increase the iser benefit of this issue i would suggest to implement a quick win:

Introduce a new sidebar entry "Deleted Notes" which is basically only a link that opens the trashbin in the browser. This is not optimal, but many people seem not to be aware of the fact that they can recover deleted notes from there.

This would give them the ability to view and recover deleted notes until a proper trashbin can be implemented in the notes server and android app.

**Comment by korelstar** [comment]
Nice quick win. Unfortunately, we can't link to a specific directory in the deleted files. The list will always contain all files -- not only notes.

What do you think, @jancborchardt ?

**Comment by stefan-niedermann** [comment]
Yeah, that's true, but still: When does a user open the trashbin from within the notes app? If he recently deleted a note (mabye by accident) to restore it. This means, the deleted note **should** be at the very top of the trashbin list when the user opens this link.

Well, as i said: It's a quick win, a compromise due the lack of time of everyone...

**Comment by korelstar** [comment]
Yeah, I'm fine with it.

**Comment by jancborchardt** [comment]
Sounds good to me too, good quick win! :)

**Comment by AndyScherzinger** [comment]
Just in case you ever want to implement the trashbin via the API (Nc14+) you can always check out https://github.com/nextcloud/android/pull/2588 and I am sure @tobiasKaminsky can help out with any questions :)

**Comment by tobiasKaminsky** [comment]
Yes, I can help you. It should be possible to only list the content of /Notes.
Maybe we/you can then also include versioning support? This is also done on android client (https://github.com/nextcloud/android/pull/2685)

**Comment by giorgosspam** [comment]
Please allow me to bring this issue up again:
If there is no connection between the smartphone and the server (e.g.  due to unavailable mobile network, server being offline, network failure inbetween, etc.) there is currently no way to restore or at least view an accidentally deleted note on the client.

**Comment by stefan-niedermann** [comment]
Starting with version `3.4.10` the Notes app will open the trashbin of the native Nextcloud app if supported ([this requires Nextcloud `3.17.x` or higher](https://github.com/nextcloud/android/pull/8405#issuecomment-852966877)). As a fallback we will continue to open the trashbin in the Web UI, for example if the Nextcloud app is too old.

I am aware that this is not quite a "real" trashbin which only show notes, but all deleted files of the user. Implementing and maintaining a complete trashbin feature is currently not on the roadmap though. By far most use cases will be covered by this compromise. Deleted notes can easily be recovered, resusing the existing features which are already present.

The drawback of this solution is, that notes which have been created and then deleted without being synchronized to the server once, can not be recovered. Given that all notes are immediately synchronized as soon as an internet connection is available and that background synchronization is enabled by default since `v3.4.2`, this is a quite special edge case which we pragmatically accept for now.
