### ISSUE TITLE
WYSIWYG mode

### ISSUE THREAD

**Issue by eemantsal** [stefan-niedermann/nextcloud-notes#272]
I think an "all-user" notes app should have a WYSIWYG interface. Not as the unique option, but as an option at least. I think that if FLOSS people wants to normalize FLOSS apps and services these should be as easy to use as proprietary commercial apps, if not, common users (my aunt, yours, our doctors who barely can use their Iphones, our pharmacist friend who doesn't even know how to write in bolds in Whatsapp...) shall keep thinking that FLOSS is a complicated and geeky thing, so better stick to Evernote even if learning how to use  "*", "#", "===", media attachment tags and not much more isn't that difficult, but you know, everything that looks like "coding"... Panic!

Saying this I'm not meaning that NC Notes app should become an HTML editor, on the contrary, I like Markdown's simplicity and easyness to edit when you learn very few and easy rules, but a WYSIWYG interface isn't incompatible and would make a lot of people's life easier. Most of the tools the majority of users would ever need would fit in a simple toolbar with a few buttons, It could even be some floating pop up toolbar, like those in [this plugin for MediumEditor](http://linkesch.com/medium-editor-insert-plugin/) (double clic on a word or single click on the image or video to see the toolbar appear) or in http://telegra.ph, https://sofish.github.io/pen/ and many other online Markdown editors that offer the user a "werid signs" free WYSIWYG interface with no clutter, and very "every-kind-of-user" friendly.
Of course the users should be able to switch between WYSIWYG and code interfaces, and set whatever they wanted as the default one. Plain text MD edition still is the quickest way to edit for experienced users.

Regards.

**Comment by stefan-niedermann** [comment]
Dear @eemantsal,

there have been lots of discussions about how powerful the notes app should be or not to be.
One target of the android app is to be a good companion to the server app (https://github.com/nextcloud/notes), so if the server app would provide a wysiwyg-interface, we would follow.
But there is an other app, NextNotes, which aims to provide a html based wysiwyg editor that is much more powerful (and complex) while this notes app is much less powerful by design. It is thought to be used for small notes like shopping notes, like "keep this in mind", not for creating rich documents nor edit word documents or create a doctors work.

For further discussion please have a look at https://github.com/nextcloud/notes/issues/111

regards

**Comment by eemantsal** [comment]
Hi @stefan-niedermann. Thanks for your rapid response.

I didn't mean increasing the "power" nor abandon Markdown to embrace HTML. I like MD and I truly believe it's sufficently potent for the vast majority of notes apps users. I just was suggesting to add a graphical interface so common users can edit their notes without needing to learm Markdown syntax and can see the results inmediately on a single pane, instead of having to switch from a code view to the definitive view and switch back to the code view to continue editing.

I'm going to move to the conversation you have pointed and shall try to express myself more clearly.
