### ISSUE TITLE
Category as ActionBar's subtitle in EditNoteActivity

### ISSUE THREAD

**Issue by korelstar** [stefan-niedermann/nextcloud-notes#285]
In order to enhance category usability, I suggest to use the ActionBar's subtitle in the EditNoteActivity to show the note's category (like the current selected category in NotesListViewActivity). We can make it even clickable: when clicking on the title/subtitle (i.e., the note's name or note's category), the CategoryDialogFragment will be opened. This provides an easier access to changing the category than using the menu item "category", since on the most devices it is "hidden" behind the three-dots button.

A drawback is, that the last-changed time is not shown anymore in preview-mode, and the edit-state is not shown anymore in the edit-mode (maybe we want also to give up the saving-state?).

What do you think?

**Comment by stefan-niedermann** [comment]
The second line shows currently the sync state. maybe we can reuse the syc-icon from the listview ind the editview (dont know yet how and where) then we could use the second line for the category, yes.

But clicking the subtitle seems to not be a common material action? i have at least never seen it and it is hard to discover. Do you have any reference for the click-action?

**Comment by korelstar** [comment]
Do we really need the sync state directly visible in the note's activity? For me, it's very distracting to see an ongoing changed from "edit" over "saving" to "saved" while typing.

Regarding clicking: If I see something that I want to change, then I try to click on it. It's a very common design pattern. The ActionBar also allows to integrate a Spinner, where you have to click on the ActionBar's title/subtitle in order to change the current selection.

**Comment by stefan-niedermann** [comment]
I don't need the sync state this prominently, but i remember it was an important request some time ago, because some users wanted to have more information.

Though i think the category is a much more valuable information, so i would say: go for it and if any users complain, we can add a sync indicator again.

About the click action: Well, okay, i have never seen this pattern on android, but i can not see it adds more complexity, so implement it. I just think, that not very much users will detect it.

**Comment by korelstar** [comment]
Okay, let's try it. But I will not start the implementation until #275 is merged.
