### ISSUE TITLE
Open in Browser

### ISSUE THREAD

**Issue by anernest** [stefan-niedermann/nextcloud-notes#296]
Please consider adding a button to preview in a stock browser pulling from server. The Markdown Editor for nextcloud incorporates plugins such as Mermaidjs that don't render in the editor preview.

**Comment by stefan-niedermann** [comment]
Hi @anernest,

> The Markdown Editor for nextcloud incorporates plugins such as Mermaidjs that don't render in the editor preview.

does it? I just tested it in my web interface with the most recent versions of nextcloud and the notes app and i could not get it work.

Is this a special setup you are running? (I assume we are both talking about the "Notes" app and not "NextNotes"?

**Comment by anernest** [comment]
Yes, I'm running Nextcloud 13.0.0, with Markdown Editor 2.0.4 and Notes 2.3.2 (both apps installed directly from the store). The following code will result in the directed graph being rendered (see https://mermaidjs.github.io/)

<pre>
```mermaid
graph TD;
A-->B; 
A-->C; 
B-->D; 
C-->D;
```
</pre>

**Comment by stefan-niedermann** [comment]
I can't see that the Notes app renders this markdown? Am i missing something here?

![grafik](https://user-images.githubusercontent.com/4741199/38571291-66183a62-3cf0-11e8-912e-a0a4ff2f0612.png)

**Comment by stefan-niedermann** [comment]
So you are using the Markdown Editor app and have the Notes App only installed to be able to synchronize with the phone?

I think this is a very edgy use case. Look: Let's say we implement the button, a click should open the browser with the Markdown Editor App (since the Notes App does not support mermaid). What will people experience who have the Markdown Editor App not installed? A 404. And detecting every time whether the Markdown Editor app is installed, is still active and not deactivated? No, sorry.

---

I really thought about it, and i might have implemented the button to open the Notes App in browser, but detect and open a 3rd party app? Sorry, but unfortunately **i have to dismiss this feature request**.
