### ISSUE TITLE
Error message doesnʼt make sense if the Notes app is not installed on the server

### ISSUE THREAD

**Issue by gergelypolonkai** [stefan-niedermann/nextcloud-notes#320]
I wanted to login with the app to my server, on which the Notes app wasnʼt installed. The error message said something about an illegal URL instead of telling me the real reason.

**Comment by kaefert** [comment]
When the Notes App is disabled on the Nextcloud Server (for example because someone installed an update and forgot to re-enable non standard apps afterwards)

The Android Notes App displays this error Message when trying to sync:

`org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONArray`

Could this maybe be changed to something more easily interpretable? Thank you!

(see also: https://help.nextcloud.com/t/nextcloud-notes-android-app-error-message/50206 & https://github.com/nextcloud/notes/issues/301 )

**Comment by stefan-niedermann** [comment]
This has been fixed a long time ago :)
