### ISSUE TITLE
A little bit more color options would be nice

### ISSUE THREAD

**Issue by bityoda** [stefan-niedermann/nextcloud-notes#356]
Just comparing to google keep or the sticky notes from micosoft in example. Not to much just something simple to categorize them a bit using colors.

**Comment by stefan-niedermann** [comment]
I see your point, bur since the Notes server app is completely file based and (intentionally) without any database, i can not see how to store or synchronize a color flag via WebDAV.

I will close this issue for now. Maybe we can go into further discussion at the server repository, and **if** we find a way to store a color property for a category (= folder), we can adapt it for ne android client.
