### ISSUE TITLE
Use monospace font

### ISSUE THREAD

**Issue by DriverXX** [stefan-niedermann/nextcloud-notes#359]
Is it possible to add a configuration option to select the font used by the notes?
I access my notes also from PC and when I read them from my phone the layout is messed up, monospace font would solve that issue.

**Comment by stefan-niedermann** [comment]
Hi @DriverXX,

i know there are beautiful mono space fonts out there and most markdown editors use mono space (at least in the edit mode). 

1. Do not at all (web interface does it neither)
2. Switch completely
3. With an option in the "View settings" area

I am struggeling with 3. because if we add it, there will be every day 3 feature requests ala "please add my font xyz-comic-sans-...". Providing all the available system fonts seems to be an overkill.

So we could provide "Sans serif, serif, mono space" without explaining which font is going to be used at all?

cc @nextcloud/designers for thoughts about mono-space font in the android notes app.

**Comment by jancborchardt** [comment]
The problem is that we use Open Sans, where there isn't a Monospace equivalent (we don't need Serif). And that would look off.

**Comment by korelstar** [comment]
A monospace font fits perfectly to a "source" mode, like in the Nextcloud-App "Markdown editor". I like this one and would be happy to see it in the Notes app (Nextcloud-App and Android-App), see also #246.

I think the comment from @jancborchardt applies to the web app, only. On Android, apps seem to be able to use a monospace font from the system.

**Comment by jancborchardt** [comment]
The issue is that a monospace font just looks very technical, and it’s not easy to read. I can see though how some people might like it, so maybe a setting here is ok. Only to switch between »Normal« (meaning sans serif) and »Monospace« though. We don’t need a serif font.

**Comment by stefan-niedermann** [comment]
Have a look at #447 for a new preference for monospace (as @korelstar mentioned, Android simple uses a system font with mono-space characters).

There are also screenshots in the PR @jancborchardt
