### ISSUE TITLE
Set pointer/caret when in visual mode to mark edit position

### ISSUE THREAD

**Issue by geniusupgrader** [stefan-niedermann/nextcloud-notes#402]
When in visual mode (preview markdown) and changing to editing the document the cursor to edit will always jump at the end of the document.

But now I want to change something at the beginning or in the middle of the document. For that I always need to scroll up when changing from visual to edit mode...

I therefore propose some type of marker in the visual mode, 
In order that, when changing to edit mode, it will start editing on this marker

**Comment by stefan-niedermann** [comment]
An edit-marker in the view-mode might be a little confusing - because you actually **can't** edit... therefore this is nothing that we will implement.

But read this comment here, it m*might* solve your problem, too: https://github.com/stefan-niedermann/nextcloud-notes/issues/227#issuecomment-309790243

**Comment by geniusupgrader** [comment]
ok
