### ISSUE TITLE
Feature request: panic button support

### ISSUE THREAD

**Issue by ZJaume** [stefan-niedermann/nextcloud-notes#412]
### Expected behaviour
Nextcloud notes app appearing on the app list of Ripple panic button and having the option to configure behaviour. The options could be:

- Hide the app
- Logout from nextcloud
- Erase all stored notes.

 
### Resources
https://guardianproject.info/2016/01/12/panickit-making-your-whole-phone-respond-to-a-panic-button/
https://dev.guardianproject.info/projects/panic/wiki/

**Comment by stefan-niedermann** [comment]
Hi @ZJaume,

i like the idea in general, but i am curious if the Nextcloud Notes (Files-) app does implement those panic mechanisms.

I know, they have support for PIN-protection, but as long as this is not implemented in the Files app it does not make sense to implement this in the Notes app because every note is also accessible via the Files app.

@tobiasKaminsky is this something you are considering to implement for the Files app? I will follow your recommendation, everything else does not make sense, as stated above.

**Comment by ZJaume** [comment]
I have alsp created an issue on the files app repo and it was accepted as a feature request.
https://github.com/nextcloud/android/issues/2697

**Comment by tobiasKaminsky** [comment]
As stated in the other issue, I am not that sure there is no easier way, e.g. have a panic button that erases the whole device, which then would also remove notes/files app and credentials…

**Comment by stefan-niedermann** [comment]
I will go for #354 (Password protection). A panic button should be implemented system wide.
