### ISSUE TITLE
Implement Single-Sign-On

### ISSUE THREAD

**Issue by schaarsc** [stefan-niedermann/nextcloud-notes#418]
There is a new idea been developed at  https://github.com/nextcloud/Android-SingleSignOn 
Should Notes-App use this library and introduce a dependency to Files-App?

Previous discussions/references: #396 #417

**Comment by korelstar** [comment]
I like the idea of providing a library for this stuff very much! However, I don't like the dependency to the Nextcloud files app.

I'm not sure, if the advantages dominate. I tend to say yes.

**Comment by schaarsc** [comment]
having a common library would be nice, but having a dependency to another app not so much...

other topics to consider:
- version dependencies: https://github.com/nextcloud/Android-SingleSignOn/issues/15
- multi account support: https://github.com/nextcloud/Android-SingleSignOn/issues/11

**Comment by stefan-niedermann** [comment]
And here is the decision made at the conference: Yes, we will use Single-Sign-On because the advantages are high enough :)

I talked to @David-Development and i am sure he will support us if we are experiencing any problems. I will post a more detailled plan how we might achive this goal as soon as i am at home.

**Comment by schaarsc** [comment]
we could take the opportunity to also think of some more refactoring ... since we will touch the code anyway something like https://developer.android.com/jetpack/docs/guide could also be considered.

**Comment by srottschaefer** [comment]
Hi, are there any news on this feature? The Nextcloud News App has implemented SSO maybe you could reuse some of the code from there?
https://github.com/nextcloud/news-android

**Comment by szaimen** [comment]
Any update on this?
Would be rellay nice to have!
(because it would be much more convenient to login)

**Comment by stefan-niedermann** [comment]
Of course. This is a huge step and nearly needs a rewrite. We focused in the last few days to bring the weblogin flow in first.

Everything else depends on how much time i can invest...

**Comment by szaimen** [comment]
@stefan-niedermann Thank you for your fast reply and of course also for all your work!

**Comment by stefan-niedermann** [comment]
# Early birds attention please :)

@korelstar @dan0xii and me have started some work to implement SSO in notes.

This is a **very early state** which still has some problems left to be resolved. (Mainly regarding migration, widgets and most importantly: The sync always performs a full sync due to a issue in the SSO lib).

If you want, you are welcome to join the work, report bugs and test the branch. We are happy about every feedback. Please provide feedback directly as comment in the PR.

https://github.com/stefan-niedermann/nextcloud-notes/pull/599

**Comment by stefan-niedermann** [comment]
Released on F-Droid (will be there in a few days). Check it out, test it, report bugs!

Thank you for patience.

Play Store will take some more time and more eye for review :)

**Comment by KopfKrieg** [comment]
Quick question: The update is still not available on F-Droid. Do you know why? Or the fastest way to contact the people from F-Droid to take a look at it?

**Comment by stefan-niedermann** [comment]
Patience, F-Droid hasn't built it (or any other app since 15. Dec.) yet: https://f-droid.org/wiki/index.php?title=Special:RecentChanges&hidebots=0&days=30&limit=500
