### ISSUE TITLE
Overall look of markdown text 

### ISSUE THREAD

**Issue by wallyreport** [stefan-niedermann/nextcloud-notes#430]
Maybe it's just me. 

The markdown text does not look sharp. The light grey background with a somewhat darker grey thin font, does not really give it a bold sharp look. 

This, combined with the huge spacing between bullet points, gives a less than impressive overall look. 

Would be great if I could change font, or background, in the settings.

**Comment by stefan-niedermann** [comment]
Thank you for the feedback.

Instead of creating a dozen new settings i would prefer to enhance the current look & feel for all users. Unfortunately the used lib does only provide some basic styling properties:

https://github.com/yydcdut/RxMarkdown/blob/master/README.md#configuration

But maybe we can open issues upstream for more customization.

Can you make concrete suggestions?

**Comment by stefan-niedermann** [comment]
The background is white and not grey. Please reopen if you can make more concrete proposals what exactly we could adjust for all users to enhance the UX.
