### ISSUE TITLE
Feature Request: color categories in notes list/widget

### ISSUE THREAD

**Issue by NeoFromMatrix** [stefan-niedermann/nextcloud-notes#434]
To make note categories more easily distinguishable I'd suggest adding a color setting for each category (not sure if this needs server side modifications). 
The note could have a colored background in the overview and widget, analog to the google calendar;
![suggested color coding for note categories](https://9to5mac.files.wordpress.com/2017/07/google-calendar-today-widget-iphone-05.png?w=800&h=400)

**Comment by stefan-niedermann** [comment]
Thank you @NeoFromMatrix,

theoretically this would be possible. The problem is, that this is something that definitely should be synced if it was available. Since the server app is completely file based and has no database, this will lead to some other problems. The Notes app ecosystem is supposed to be fully supported with only-file-sync-clients, too.

To be honest  i have no idea how this could be implemented without adding a database at the server side (which could not be synced with only-file-sync-clients) or without introducing some kind of custom format which has to be parsed....

**Comment by NeoFromMatrix** [comment]
Not feasible under these circumstances. 
I guess this could be closed.

**Comment by stefan-niedermann** [comment]
okay, if anyone else has a good idea how to achieve this, just comment, i would be happy if we could eventually find a solution (even if i don't think it's possible).
