### ISSUE TITLE
[Feature Request] Add confirmation before note deletion

### ISSUE THREAD

**Issue by kingkoronov** [stefan-niedermann/nextcloud-notes#440]
I would think it would be enough to just have the "hold note and then tap garbage icon in top right corner" action to prevent accidental deletions, but I accidentally deleted a note today that I badly needed without even noticing it was deleted (to clarify, I was trying to open that note while not paying close attention, later noticing it was gone and only guessing how it happened). It would be nice if there was an extra confirmation dialogue after you select the deletion button.

**Comment by stefan-niedermann** [comment]
Hi, have you tried to recover it via the webinterface from the trashbin?

**Comment by kingkoronov** [comment]
Yep, that worked. Thanks. If you can restore, there is probably no need.

**Comment by stefan-niedermann** [comment]
Okay, i think we already have good enhancements to protect from accidential deletion:
- Swipe 2 Delete is beginning with v0.18.0 only on one side instead of both
- After swipe 2 Delete one can "undo" the deletion from within the android app for several seconds (toast at the bottom appears)
- Notes can be restored via the webinterface
- We are planning to implement some kind of trashbin

Therefore i will close this issue for now. We had some similiar issues where we explained in long term why we prefer *undo* over *confirmation*, there are several articles and blog posts out there that explain why it is better.

Regards
