### ISSUE TITLE
Better icon for top left: Checkmark

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/nextcloud-notes#468]
Currently the "back arrow" icon in the top left is a bit misleading or confusing. You are not sure if the note will actually get saved if you tap it (which does happen, gladly).

A better icon would be a checkmark icon:
https://material.io/tools/icons/?search=check&icon=check&style=baseline

Just like Google Docs is also doing it (disregard:
![](https://cdn6.aptoide.com/imgs/f/4/d/f4d84692c6783803a7665dfeba82800f_screen.png?h=1080)

**Comment by korelstar** [comment]
Your screenshot shows the situation when a text is selected. Here, the checkmark makes sense, since you confirm the formatting when tapping on it. This is a typical design on Android.

However, according to the screenshots in Google Play, even Google Docs doesn't use the checkmark when in normal edit mode:

![Screenshot from Google Docs](https://user-images.githubusercontent.com/6277619/44953439-ca2b5e00-ae95-11e8-91c1-a2ada25f59e0.png)

According to the Android guidelines, every app should save the current state without explicit confirmation. Hence, I don't think that a checkmark is needed.

**Comment by jancborchardt** [comment]
> According to the Android guidelines, every app should save the current state without explicit confirmation. Hence, I don't think that a checkmark is needed.

Ok, if it’s explicit guideline then I guess it’s fine. Thanks for the info! :)
