### ISSUE TITLE
Widgets aren't working anymore

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#482]
cc @dan0xii creating single note or list widgets does not work anymre. Can you please have a look?

**Comment by dan0xii** [comment]
Where are you seeing this happen? On the master branch? They're both working fine for me in both themes on phone and VM.

**Comment by stefan-niedermann** [comment]
Two users complained about it directly after i released v0.22.2, i asked them for screencaptures because i can not reproduce it too.

Steps to reproduce are as simple as add one of the widgets to the homescreen. it simply "does not appear"/

**Comment by dan0xii** [comment]
I'll try testing through other versions of android and see if that produces any different results.

**Comment by stefan-niedermann** [comment]
One of the reporters is using Marshmallow (6.0).

**Comment by StefanPp** [comment]
I am one of the guys with this problem using
0.22.2
on
LGE LG-H440n
Marshmallow 6.0

I made a short viedeo demonstrating the problem
[Video](https://cloud.dawesys.de/index.php/s/CHCJSTHbkSf47kH)

- drag the Widget to empty desktop
- choose the item
- no reaction, just returning to the still empty desktop

I tried
re-install, empty desktop, empty cache etc.

Seems to be a problem, that the selection of items is not returned to the widget.

**Comment by tecufanujacu** [comment]
Me too on Android 6.0.1, Nextcloud Notes 0.22.2 and the problem #405 persists.

**Comment by dan0xii** [comment]
I spotted a bug in both widgets' code for the dark theme. I've fixed that now and have been testing on my phone with positive results so far.

If you have the ability to build from source then the changes are in this branch: https://github.com/stefan-niedermann/nextcloud-notes/commit/4cd609393f5dfcc2222cf25340133678f52d4287

**Comment by kukukk** [comment]
Hi!

I also have this problem on a Sony Xperia XZ1 Compact. I tried the latest version (0.22.2) from F-Droid, the latest version from master and also from the widget5 branch.

**Comment by dan0xii** [comment]
Are you also on Android 6.0?

**Comment by kukukk** [comment]
Sorry, I accidentally sent my comment without finishing it. I have updated it...

**Comment by kukukk** [comment]
If you have some ideas where to put some debug output, please, let me know...

**Comment by kukukk** [comment]
I quick update: it works with version 0.21.0, but it's no longer working with version 0.22.0.

**Comment by kukukk** [comment]
[git checkout 8d39a10c3db25136dbacaf73cc36e217d583ece6](https://github.com/stefan-niedermann/nextcloud-notes/commit/8d39a10c3db25136dbacaf73cc36e217d583ece6) - the widget works
[git checkout fa3c3f4faa79a9843c138a0ec5c80c1888de17a7](https://github.com/stefan-niedermann/nextcloud-notes/commit/fa3c3f4faa79a9843c138a0ec5c80c1888de17a7) - the widget doesn't work
[git checkout 7766f6504323b3e12149b0710d752c231726d83f](https://github.com/stefan-niedermann/nextcloud-notes/commit/7766f6504323b3e12149b0710d752c231726d83f) - the app doesn't start, so I can't check.

So, I think that the problem is caused by one of the commits made on Aug 31 or Sep 4. Does it help, or do you need further refine?

**Comment by dan0xii** [comment]
> git checkout 8d39a10c3db25136dbacaf73cc36e217d583ece6 - the widget works
git checkout fa3c3f4faa79a9843c138a0ec5c80c1888de17a7 - the widget doesn't work
git checkout 7766f6504323b3e12149b0710d752c231726d83f - the app doesn't start, so I can't check.

> So, I think that the problem is caused by one of the commits made on Aug 31 or Sep 4. Does it help, or do you need further refine?

> Update:
> After backporting the modifications from "Notes has stopped on first run", I think that the commit causing the problem is "Dark themes for single note and note list widgets."

Appreciate the troubleshooting. Is the problem you're encountering the same as the one shown in @StefanPp's video?

@StefanPp, what launcher are you using? I haven't been able to reproduce the problem at all.

**Comment by kukukk** [comment]
Yes, it seems to be the same:
 - the CreateNote widget works
 - with the SingleNote and NoteList widgets the configuration screen appears, but after selecting the note/category nothing appears on the screen

I also tested it on a Nexus 6P with Android 8.1 and the problem is not present.

Unfortunately, there is no useful message in the logcat. If you have any idea what to test, or if you prepare a commit with debug output you consider helpful I can run it on my Xperia where I can reproduce the problem.

**Comment by dan0xii** [comment]
I've updated the widget5 branch with some logging. Would you try that and send me a copy of the logcat? Either paste it here or email to dan0xii [at] pm [dot] me.

**Comment by kukukk** [comment]
Logcat sent by email. In case you have not received it, let me know, and I will paste here.

**Comment by StefanPp** [comment]
@dan0xii
I use the orginal LG launcher that came with my LG Spirit H440N

**Comment by dan0xii** [comment]
Much thanks to @kukukk who has provided a lot of troubleshooting and testing information for this fix. We think we've figured it out now but could do with testing.
