### ISSUE TITLE
Is it really needed to reload the notes when leaving the about and settings menu?

### ISSUE THREAD

**Issue by radoeka** [stefan-niedermann/nextcloud-notes#502]
Just wondering is it really to check for updated notes, after visiting the menu options: about and settings.

When visiting about, nothing is changed in that menu, is that require a update from the server anyway?

Similar for the settings menu, especially when no changes are made at all.  Perhaps some of the settings require a update, perhaps that can be memorized by app, and only contact the server when leaving the settings menu and the need to contact the server has been set.

(I think that the app should avoid to contact the server as much as possible, especially when connected mobile 3G/4G)

**Comment by stefan-niedermann** [comment]
We currently do not have conflict handling (like merging) and for this reason we try to update the notes as often as possible, so we can avoid conflicts. I understand, that not everyone has always wi-fi and limited data (e. g. indeed i only have 200 MB per month myself) - but unless we do not have a conflict handling solution (see #406 and #161) it's better to "waste" data than data loss. Instead of pulling based on a timer (which would be even worse), we decided to refresh everytime when the user might probably make changes to the notes) 

(closing this as it would be resolved if the linked issues will be fixed, don't feel offended, we can talk about it, it's just for issue tracking :) )

Hope this clearifys the reasons behind this decision.

**Comment by radoeka** [comment]
Thanks.  And no offence, just thanks for a useful app!
