### ISSUE TITLE
Crash when selecting, again

### ISSUE THREAD

**Issue by SqueeZen** [stefan-niedermann/nextcloud-notes#508]
Hello,
The issue occurring again since the few releases ...

_Originally posted by @SqueeZen in https://github.com/stefan-niedermann/nextcloud-notes/issues/431#issuecomment-443488002_

**Comment by stefan-niedermann** [comment]
Can you please verify whether this issue was fixed for you with https://github.com/stefan-niedermann/nextcloud-notes/pull/622 ? I am still not able tk reproduce this on any of my physical devices nor on virtual devices.

You can get the latest version on F-Droid and on Play Store beta track: https://play.google.com/apps/testing/it.niedermann.owncloud.notes

**Comment by stefan-niedermann** [comment]
Closed because of missing feedback.

Please check if the issue still occurs in the current version.

If so, please provide exact steps to reproduce and a minimal sample note, which causes the error.

Also please post more details about your device.

Thank you
