### ISSUE TITLE
Cannot Connect with Two Factor Authentication Enabled on Server

### ISSUE THREAD

**Issue by ZitZ** [stefan-niedermann/nextcloud-notes#509]
Not sure if it is the api or the app. Throws java.io.FileNotFoundException in toast notification complaining about the api endpoint.

**Comment by stefan-niedermann** [comment]
That's right, the app is currently not able to authenticate via 2-factor-authentication.

We are planning to switch to the single-sign-on in the future to avoid these kind od problems (#418).

i'm sorry but you will have to wait until this feature has been implemented.

please be aware that a login with ownCloud will no longer be possible.

If you need further support, please feel free to contact me directly via eMail.

Regards

Stefan Niedermann

**Comment by ZitZ** [comment]
Oh no problem. It wasn't an urgent need for me. Thanks for the great code! Keep up the good work!

**Comment by Foggalong** [comment]
Also ran into this issue. Is there any feel for when it will be implemented / anything we can do to make it happen?

**Comment by teatreeoilchocolate** [comment]
Hi there.
I also added a comment to a ticket on the other bugtracker, because I found it before this ticket.
https://github.com/nextcloud/notes/issues/198#issuecomment-565607306

System is Nextcloud 17.0.1, Notes-App 3.0.3 and Androidapp is 1.0.1 .

And I can also add to the people that have written before me.
Thx for the project :D .

**Comment by teatreeoilchocolate** [comment]
Just wanted to let you guys know. The SSO implementation is working and it solves the problem with the 2FA.
You guys are gods.
Thank you very much.
Works like a charm.

**Comment by stefan-niedermann** [comment]
Glad to hear that :) Please feel free to rate the app on the Play Store if you want.

Have fun with the app 🚀

**Comment by Foggalong** [comment]
What's the SSO implementation? :open_mouth:

**Comment by stefan-niedermann** [comment]
Nextcloud Notes will starting with version `2.0.0` support the **S**ingle **S**ign **O**n login flow from the [official Nextcloud app](https://play.google.com/store/apps/details?id=com.nextcloud.client).

This will allow users to simply sign on reusing the (mostly) already configured account from the offical Nextcloud app.

Also, the Notes app is then able to use the network stack of the offical Nextcloud app, which ensures, the Notes app will work in *any* case where the official Nextcloud app works, too (e. g. special setups with self-signed certificates, 2nd factor auth etc). :rocket: 

For users another benefit is security :lock: - The Notes app will no longer store any password and does not have to care about keeping credentials secret.

Last but no least: Using the network stack of the official Nextcloud app allows us to drop very much from our code base and allows us to develop and maintain new features more easily because we now have way less ballast :zap:
