### ISSUE TITLE
Ability to join files likes screenshots or fotos 

### ISSUE THREAD

**Issue by tclavier** [stefan-niedermann/nextcloud-notes#512]
As user i want to be able to join files at note. My objectiv is to add comments, tags and other words to find a photo very quikly in future.

**Comment by stefan-niedermann** [comment]
Dear @tclavier i understand your wishes, but first the server side app has to support those kind of things. The android app will follow if this will be implemented on the server side: https://github.com/nextcloud/notes/issues

Please note, that there are already some issues in the repository and that not everything can be implemented because the Notes app is designed to be able to work without a database and with the simple file sync client.

In the meantime you can use tagging and comments via the files app (see `Notes`-folder).

Regards

**Comment by tclavier** [comment]
IMHO, you can reopen this bug and make a dependency on https://github.com/nextcloud/notes/issues/74
