### ISSUE TITLE
Invalid login

### ISSUE THREAD

**Issue by realrufans** [stefan-niedermann/nextcloud-notes#530]
Why can't I login ?
I have an account with a serve [ carnet.live ]

But I can't login via nextcloud notes.

**Comment by stefan-niedermann** [comment]
Is the "Notes"-app enabled on the server? (**not** "NextNotes")

**Comment by realrufans** [comment]
I don't think I understood that message. I got that a error message while trying to sign-in. I have been able to syncronize my notes between carnet and nextcloud. I don't know if that's what you mean. If not, how can I enable app on the server?

**Comment by stefan-niedermann** [comment]
I just created an test account at carnet.live. [They do **not** have the "Notes"-app installed](https://apps.nextcloud.com/apps/notes), therefore the android client **can not** work. You can ask them to install the app on the server, otherwise there is unfortunately no possibility to use this android-client with this server.

**Comment by realrufans** [comment]
Wow. Okay thank you ..

But it would have been nice if we can use any server with nextCloud-Notes.

Why isn't that so ?


And how can I see list of enabled apps ? Thanks.

**Comment by stefan-niedermann** [comment]
> Why isn't that so ?

The problem is, that every Notes-App is working slightly different. For example one supports images, one is using HTML, one is using Markdown, one can handle folders, another one uses tags/labels.

It is just impossible to create an app that can use every backend that is available out there - every app is moving, changing APIs etc...

Visit https://carnet.live/index.php/settings/user

There you can see the original top bar, which looks like

![bildschirmfoto vom 2019-02-10 10-14-08](https://user-images.githubusercontent.com/4741199/52531893-c0e3ce80-2d1c-11e9-8877-5f57af0b70aa.png)

You can see that there are only enable two apps - The default "files"-app and the "Carnet"-app (which i don't know).

Other providers have enabled much more apps, like "Mail", "Calendar", "Contacts", "Notes", "Deck", and so on...

**Comment by realrufans** [comment]
Wow! You answered everything. Thanks

I'm actually looking for an enabled open source app. 😁

**Comment by stefan-niedermann** [comment]
Just trying to help :)

Have a look at https://nextcloud.com/signup/

There are some free providers (limited storage). The list also shows which apps are enabled. There you can find a server which has the notes app enabled.

**Comment by realrufans** [comment]
Thank you 👍
