### ISSUE TITLE
unnecessary connection error notification

### ISSUE THREAD

**Issue by fockr** [stefan-niedermann/nextcloud-notes#544]
Hi there,

i use my phones flight mode frequently. **Every time** I turn it off in order to connect to the internet I get an error message (java.net.connectException) at the bottom of the screen which is informing me that the connection to the server failed.

Now this is problematic for two reasons:
- the message covers the keyboard and it becomes very challenging (and besides annoying) to type and
- the message does not help at all - respectively has no informational value to the user because a) an internet connection is present and working and b) it is unnecessarily catching attention.

My suggestion is to implement a checkbox in the settings menu which enables the user to turn off this notification.

Best regards,
w

P.S. Thanks a lot for the nice app. Apart from this error it is very usable and helpful in helping me to keep my data private.

**Comment by stefan-niedermann** [comment]
Should be fixed by switching the network stack from the own implementation to ne official files app beginning with v2.0.0.

Please reopen, if the issue still occurs with this (or higher) version.

This version is already available on F-Droid and on Play Store beta track: https://play.google.com/apps/testing/it.niedermann.owncloud.notes
