### ISSUE TITLE
Bullets in lists are barley visible

### ISSUE THREAD

**Issue by Hund** [stefan-niedermann/nextcloud-notes#548]
They should have the same colour as the text and be a bit larger for good visibility.

Thanks you for your time! 

![IMG_20190321_224036](https://user-images.githubusercontent.com/320498/54787025-ca6d2a00-4c2a-11e9-9376-b7049e7386f2.jpg)

**Comment by stefan-niedermann** [comment]
This is strange - i can reproduce https://github.com/stefan-niedermann/nextcloud-notes/issues/501 - but only with the dark mode. on the light mode the bullets are black.

Can you provide more information:

- Which version?
- Play Store or F-Droid?
- Android version?
- Did you ever use the dark theme before?

**Comment by Hund** [comment]
> Which version?
0.24.3.

> Play Store or F-Droid?
F-Droid

> Android version?
8.1 (Lineage OS 15.1)

> Did you ever use the dark theme before?
I tried it once.

Now that you mention it, I have noticed that my calculator is not always the same colour. When I checked Nextcloud Notes now the bullets was black, but tiny and barley visible still. 

I then checked the system settings to see if there's something going on there. I remembered that you could change between dark and light mode, but that might just affect the system theme? After checking the settings the bullets is back to its light colours again.

**Comment by stefan-niedermann** [comment]
Well, this sounds likely like a problem with your Lineage build because you are experiencing similar theme-affected problems with other apps. Is the Lineage build official?

Are you able to reproduce the issue on another smartphone?

**Comment by Hund** [comment]
That sounds resonable. It is official, I could try updating it.

I don't have access to any other phone.

**Comment by Buntstich** [comment]
Same issue here

Samsung A40: One UI v1.1, Android v9, original Theme
Nextcloud Notes: v0.24.3, Play Store

A40 Day mode + NCN Light Theme: very small black bullets
A40 Day mode + NCN Light Theme: light grey Navbar 
A40 Day mode + NCN Dark Theme: very small black bullets
A40 Day mode + NCN Dark Theme: white Navbar

A40 Night mode + NCN Light Theme: very small light grey bullets
A40 Night mode + NCN Light Theme: light grey Navbar 
A40 Night mode + NCN Dark Theme: very small white bullets
A40 Night mode + NCN Dark Theme: white Navbar

I hope this helps to figure out where the issue comes from.

**Comment by stefan-niedermann** [comment]
Cannot reproduce on version 1.0.0. Please open a new issue if problem still occurs.
