### ISSUE TITLE
Sync error icon 🔄

### ISSUE THREAD

**Issue by cptechnik** [stefan-niedermann/nextcloud-notes#553]
In my environment, I have sometimes problems with sync... sometimes it's just the missing WiFi, sometimes it's because server is down.

Is it possible to 
- build in a icon or timestamp to see the sync status, 
or 
- get a permanent system alert if the sync didn't works ...hmmm ten times ? ... as the normal sync...? (More than the toast alerts... they disappear... to fast...)

**Comment by stefan-niedermann** [comment]
I can't see any benefit. What will you do if you see the icon? Do nothing? Trigger the sync manually (which executes exactly the same as when one starts the app)?

Also a permanent notification will what benefit have over displaying the user a toast on a failed sync?

**Comment by thgoebel** [comment]
*Situation A: App start*

Currently after an app start the small circular progress indicator just keeps spinning indefinitely when I'm not connected to a network. For me, that's cue enough that a) my notes are not yet up-to-date and b) I need to check my connection.

Additionally, the current behavior is easier for the user: there is no additional action needed, no button to click when the network becomes available: the pending sync just completes.

*Situation B: pull-to-refresh after some app usage*

Regarding the point that the "Sync failed"-toast disappears quite fast: true that, I have missed it in the past as well. However the un-synced icon (🗘) remains next to any note, so there is still a cue that the note is not yet synced.

=> In either case: If this were to be implemented, a suitable UI element would be a [banner](https://material.io/components/banners/banners.html) rather than a system notification. But I think it's good the way it is now.

**Comment by stefan-niedermann** [comment]
I agree with @thgoebel.

In version `2.4.6` the toasts were replaced by a snackbar which can open a further dialog.
This way, one does not need to hurry up to read the content but can simply watch it in the dialog (and copy it for reporting etc.)

I haven't been aware of the `banner`-UI-element, maybe fits even better, we might change this in the future.

---

But all in all i think, it is more important to fix the actual bugs (for what we urgently need information about what exactly went wrong) than to display "hey this note hasn't been synced yet. too bad!"
