### ISSUE TITLE
Black theme for OLED devices

### ISSUE THREAD

**Issue by Lynnesbian** [stefan-niedermann/nextcloud-notes#557]
The current dark theme's background colour is [not quite black](https://github.com/stefan-niedermann/nextcloud-notes/blob/58e663b30f2e435f0591fbd9eea5a8b83b95df7d/app/src/main/res/values/colors.xml#L33). Adding a "true black" theme, or changing the current theme to use a background colour of #000, would enable OLED devices to save battery while using the app.

**Comment by stefan-niedermann** [comment]
While i understand the supporters of a true black theme, i came to the final conclusion that i do not want implement this feature.

While the feature wouldn't be too hard to implement, i can see a big maintenance problem here.

I simply have not enough time to make sure, that every existing and new feature is working properly **and** looks nice in three different themes.

Sorry, but i want to spend more of my rare sparetime to implement features that are more useful for the majority if the users.

After all, we also can save way more battery (for all users) if we optimize e. g. the sync menchanism than if we lower `#222` to `#000`.

**Comment by szaimen** [comment]
@stefan-niedermann so then why not just lower it to #000 in dark mode? This would solve the problem of having to maintain three themes. Also it would provide a dark mode as well as amoled mode in one theme.

**Comment by stefan-niedermann** [comment]
Because text on a `#000` is harder to read as many resources and studies proof (see e. g. [UX Planet](https://uxplanet.org/8-tips-for-dark-theme-design-8dfc2f8f7ab6).

However, the Material Design Specification recommends `#121212` as background color. Therefore i will have a look whether we can lower the background color to this level. Currently i only found samples which have elevated elements with a brighter gray on top (e. g. cards) and i didn't found a sample yet where the text is directly on the primary background layer (like in our lists or in the edit mode).

I will have a look and **maybe** i will lower the color to the mentioned `#121212` **if** i find a resource for it. No promises.

**Comment by szaimen** [comment]
Okay, thanks!
Thats more then we could hope for!

**Comment by stefan-niedermann** [comment]
Background will be `#121212` beginning with v2.11.0.

**Comment by szaimen** [comment]
Thank you very much!
