### ISSUE TITLE
Password plain text

### ISSUE THREAD

**Issue by mcking230** [stefan-niedermann/nextcloud-notes#562]
Password in plain text stored in /data/data. Not secure a little bit

**Comment by stefan-niedermann** [comment]
Well, the password has to be stored at some place. If you have a better idea where to put it, a pull request would be welcome :)

The password is only readable on rooted devices, a technical advanced user knows the risk.

There is the plan to implement Single Sign On in the future - At this point in time we can drop the password handling completely and move the credential handling to the files app.

But as i stated: Where would you save a password?

**Comment by mcking230** [comment]
The question here is not where to store, but how.  Is not it better to store in the form of salt, hash or something else?

**Comment by stefan-niedermann** [comment]
This is not possible since the login rquires the original password. From a hash it is not restoreable.

Using the 2FA-app i think its possible to create at least one app specific password to shrink the security risk.

But like i said; For the current implementation a plain text password is required to authenticate and the long-term goal is to switch to Single Sign On :)
