### ISSUE TITLE
New note view enhancements

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/nextcloud-notes#57]
The new note view should have a back button top left so one can go back. Of course it should save then. The x button is better removed since it's too close to the save button.

And of course autosave should be in this view too.

**Comment by HeaDBanGer84** [comment]
I would recommend to merge the "NewNoteActvity" with the "EditNoteActivity" They have to be pretty similiar anyway and its esier to maintain.
Also wouuld recommend to move the accept Icon from the ActionBar to a floatingButton in the bottom right like its recommended in the design guidelines.
Sorry for mixing these things in one Issue but I think they can also be fixed at once. If everybody agrees.

**Comment by jancborchardt** [comment]
@HeaDBanGer84 do you mean »Make note directly editable #3«

**Comment by HeaDBanGer84** [comment]
Nope, its more or less just code reorganisation. At the moment editing a Note and creating a new one are to complete different classes which doesn't share much code or layout. In fact creating a new Note can be done by creating an empty note and edit it. If handle note creation that way the layout can be shared and also of lot of code can be reused. That means if you fix a bug in the EditNoteActivty its automatically fixed in the CreateNoteActivity (because of the shared code/layout).
Because #50 allready fixed this would solve that issue to (same reason).
I can do this, but I would like to hear @stefan-niedermann oppinion before I start.

**Comment by stefan-niedermann** [comment]
Yeah, we can merge create and edit (code-wise).

> The new note view should have a back button top left so one can go back. Of course it should save then. The x button is better removed since it's too close to the save button.

- [ ] Create / Edit should have a back button top-left so one can go back (currently only in edit)
- [ ] Create / Edit should have auto save (currently only in edit)
- [ ] Create / Edit should have an X-Button in the top-right corner, because: 
  - It is no longer too close to the save button since the save button will be removed (auto-save and auto-save on top-left back button
  - Pressing the top-right X-Button allows an user to cancel his editing (I noticed this is a strange behaviour - auto-save is nice, but when i have done something i'm not able to cancel my changes)
    - This means technically we have to store a copy of the edited note object until the user leaves the activity - if he presses the X-Button the copied object can be used to restore the original status.
    - On Creation pressing the top-right X-Button technically means to delete the (previously auto-saved) note.

@HeaDBanGer84 Doesn't make sense to work on this issue together - do you want to take it over? Starting from the current upstream master branch?

**Comment by HeaDBanGer84** [comment]
I startet on implementing #61 . See https://github.com/HeaDBanGer84/OwnCloud-Notes/tree/SyncService for my changes so far. After finished I can start with this one. If you not have finished it first ;-)
