### ISSUE TITLE
ownCloud no more supported

### ISSUE THREAD

**Issue by testcocoon** [stefan-niedermann/nextcloud-notes#681]
ownCloud is no more supported by nextcloud-notes 2.x.
It is necessary to install the version 1.0.1 from F-Droid to use it.

If ownCloud is no more supported, it would be good to publish a fork on F-Droid for ownCloud.

**Comment by stefan-niedermann** [comment]
Yes, this is correct. ownCloud does not show any active development for it's note pendant and constructs like "Nextcloud Notes on ownCloud" are too bleeding edge cases.

In fact, there is no official support for ownCloud from us since years. Though we want to move forward and this includes usage of new features like Single Sign On which are only provided by Nextcloud.

You can feel free to make a fork, it's open source after all, but personally i would recommend you to switch to Nextcloud if you don't have any important reasons against it.
