### ISSUE TITLE
Display modified time of notes

### ISSUE THREAD

**Issue by kmantel** [stefan-niedermann/nextcloud-notes#709]
I need to know the time and date notes were created and/or modified. This is a feature in pretty much every note-related application I've used. #12 Added basic categorization based on times, and the Notes web app displays the ![time and date on a "Details" pane](https://user-images.githubusercontent.com/1592123/73435366-62a26800-4340-11ea-8c6d-4f8c759965b8.png)

Without implementing a Details menu, the modified time and date could be placed, for example, below the blue separator/bottom of screen in the edit/view note pane, and in the note summary in the list view.

**Comment by stefan-niedermann** [comment]
Hi @kmantel,

thank you for your request.

> This is a feature in pretty much every note-related application I've used.

Well, we aren't like "every note-related application" 😉 . We are aiming for a minimal design which allows users to write completely distraction free down simple notes. Therefore the argument, that we need it, because every other notes app has it too, is invalid.

I'd like to learn more about the use-case - why is it necessairy in your workflow to know the *exact* time when a note has been modified the last time?

If it is a use-case from which we assume could be relevant for the majority if the users, we can talk about how we can support it without adding visual noise for other users.

**Comment by kmantel** [comment]
I don't exactly see how an automatic timestamp is distracting; to me it *is* a minimal feature. I don't know how I can justify it to you -i t is often the main reason I even take a note, to know when something happened, for example.

**Comment by stefan-niedermann** [comment]
> to know when something happened, for example

Then the `modified` date wouldn't really be a good marker, because if you look at the note and fix a typo or toggle a checkbox, the `modified`-date will change and the information is incorrect (best case: worthless, worst case: miskeading or wrong information).

Do we agree at this point?

To have a reliable information, you would either need a separate field like on a calendar (which is out of scope for this app) or directly write the date into the note itself like

```
# Diary

2020/01/02: Went fishing with friends
```

**Comment by kmantel** [comment]
Obviously a "created" and "modified" timestamp is ideal, but since that is not included on the main nextcloud interface, I did not propose it. We do not agree however, and I see little chance of convincing you.

**Comment by stefan-niedermann** [comment]
Don't get me wrong, i am open to change my mind. But i think, we should not add viual elements without a reason or a **need**.

And for the use-case you mentioned, the `modified`-date will simply not work well. If you have other example or workflows, i would be happy to hear them, so we can determine whether the proposal is an enhancement for the users or not (and if it doesn't provide value, it's visual noise - because the content has to be scanned and mentally processed).
