### ISSUE TITLE
Feature Request: Disable sort by date

### ISSUE THREAD

**Issue by pmprog** [stefan-niedermann/nextcloud-notes#767]
Hi,

 Would it be possible to add an option so that i could just list all my notes sorted by "title"?
Alternatively, keep the date sort, but remove the date headers, as to compact the list
When i come to my notes, I'm not interested in when they were last updated, only the content of them; and i see nearly as much blank space and headers as i do items on my screen

![Screenshot_NCN](https://user-images.githubusercontent.com/1705629/77210175-390fec80-6af8-11ea-900e-c08479e7ccd5.png)

Cheers

**Comment by stefan-niedermann** [comment]
Hi @pmprog,

thank you for your request. Unfortunately this is nothing we are currently planning to implement.

- The sections are needed when sorting by date for a better orientation and help to quickly scan the notes
- I can not see any valid use case where alphabetical order is superior to a date based sorting. The problem is, that offering a setting for this will of course be visible for every user, most of them won't need it. This will cause visual noise which i want avoid.
- Please consider using a category for the notes (category view is sorted alphabetically) or use favorites to keep the important notes at top in combination with the search function
