### ISSUE TITLE
Unable to view/access markdown Notes on Android created by Notes

### ISSUE THREAD

**Issue by tgrrr** [stefan-niedermann/nextcloud-notes#782]
If I create a markdown note in my NextCloud account folder, then it is accessible to open with Notes, and with the App that created it.

When I create a markdown file with Notes, I can access that file on my laptop with NextCloud.

However, I cannot find/edit the file on my Android with other Android apps.

I'm looking for the file in:

`/storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/<NEXTCLOUD-ACCOUNT>/`

It does not seem to appear elsewhere in the file system when I search with other apps.

There also doesn't seem to be a setting option to move where the files are saved.

**Comment by stefan-niedermann** [comment]
The android app stores notes for performance reasons in a database. You won't be able to access them with other apps directly.

You can share the content of notes using the three dots menu to other apps or you will have to go the way using the main Nextcloud android app in order to sync the actual files.

**Comment by stefan-niedermann** [comment]
Edit: I assumed you are using this app on your device: https://play.google.com/store/apps/details?id=it.niedermann.owncloud.notes

Bit based on your search location i guess you are only using the main Nextcloud android app: https://play.google.com/store/apps/details?id=com.nextcloud.client

In this case you are looming right, but you will have to download the notes files first because this app doesn't sync the whole cloud by default. Just long-press on the "Notes"-folder and click "Synchronize". The files should then be on your device.

**Comment by stefan-niedermann** [comment]
Please reopen this issue if you have any further questions :slightly_smiling_face:

**Comment by tgrrr** [comment]
That's correct assumptions. For reference: do you know if I will have to continually manually syncing the _Notes_  folder?

**Comment by stefan-niedermann** [comment]
Which of the both linked apps are you using?

1. https://play.google.com/store/apps/details?id=it.niedermann.owncloud.notes
2. https://play.google.com/store/apps/details?id=com.nextcloud.client
