### ISSUE TITLE
Making a note favorite changes the file name to the first line

### ISSUE THREAD

**Issue by yarray** [stefan-niedermann/nextcloud-notes#818]
**Describe the bug**
When clicking the yellow star, the note's title along its file name will become the first line permanently.

**To Reproduce**
1. Sync a file `hello.md` with content:

```
Hello World
1
2
3
4
```

2. Click left star to make it favorite

The title becomes "Hello World" and the file name becomes "Hello World.md"

**Expected behavior**
Do not change the title and the file name.

**Screenshots**

**Server**
 - Nextcloud-Version:  18.0.4（self hosted）
 - Nextcloud Notes-Version (server app): 3.3.0
 - PHP-Version: 7.3.17

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 2.11.12
 - F-Droid or Play Store: F-Droid
 - Device: Xiaomi 8
 - Android-Version: 10 (LineageOS 17.1)

**Stacktrace**

**Comment by korelstar** [comment]
This is because the Android app doesn't implement the new API v1, yet. But we could improve the stated scenario by changing the behavior of the old API v0.2 a little bit: The title is only changed, if the content is changed - i.e., if the content doesn't change (for example only the favorite is toggled), the title is kept as is.
@stefan-niedermann what do you think of this approach?

However, if you change the content, the title/filename will still be changed until the Android app implements the new API with manual title.

**Comment by stefan-niedermann** [comment]
I'd rather focus on implementing API v1.0 instead of hacking around API v0.2.

**Comment by korelstar** [comment]
True.

**Comment by stefan-niedermann** [comment]
Closing in favor of #786
