### ISSUE TITLE
Easily add tick box and  bullet point

### ISSUE THREAD

**Issue by lackyluuk** [stefan-niedermann/nextcloud-notes#819]
My proposal is to add the entries "Tick Box" and "Bullet Point" to the 3-dot menu while editing a note.
So that it automatically adds a "[ ]" or a "*" to start a list. This would save a lot of time when editing on a smartphone.

Further I noticed that the list only continues with a tick box or bullet point (by hitting Enter) after switching to View Mode and then back to  Edit Mode. Otherwise it will just start an empy line.

If I am completely stupid and this functionality is already implemented and I don't find it, please let me know :)

**Comment by stefan-niedermann** [comment]
When selecting text there is a pop up menu containing "Copy", " Cut", "Select all" and so on.

It also contains the menu item "Checkbox" and will make the current line a checkbox item.

This also works on empty lines.

I will not add fifty always visible buttons nor flood the three-dots-menu, because we aim to br *distraction free* and provide only *context based formatting*. sorry 😉

**Comment by lackyluuk** [comment]
Fair enough! I was not aware of this way to add it. 
Thanks to you!
