### ISSUE TITLE
SSO error

### ISSUE THREAD

**Issue by keunes** [stefan-niedermann/nextcloud-notes#835]
**Describe the bug**
An SSO permission error is shown on every start-up and frequently while using the app, when SSO has not been enabled (as account was added before).

I believe rejected access to the accounts on my phone (as I'd rather not register my private account in core Google modules). This worked when I installed the app; the error was introduced with an update.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the app
2. See error

**Expected behavior**
Don't show error when I'm already successfully logged in.

**Screenshots**
![Screenshot_20200522-110531](https://user-images.githubusercontent.com/11229646/82654975-ca4b2e80-9c21-11ea-90a5-b4ec261353ba.png)

**Server**
 - Nextcloud-Version: 
 - Nextcloud Notes-Version (server app): 
 - PHP-Version: 

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 2.12.1
 - F-Droid or Play Store: PS
 - Device: Fairphone 2
 - Android-Version: Fairphone OS 19.11.2 (Android 7.1.2)

**Comment by stefan-niedermann** [comment]
Which version did you have installed before the update?

**Comment by keunes** [comment]
Ouf, that I wouldn't remember, but I bought & installed the app 13 January this year. Can you deduct which version that would've been?

**Comment by stefan-niedermann** [comment]
When you say, that the message appeared the first time after an update, i assume that you previously used version`0.x.x` or `1.0.0`. However since version `2.0.0` we rely on the Single Sign On mechanism of Nextcloud for many reasons like security and compatibility.

In order to further use the app, you have to grant the permission, so the Single Sign On mechanism works and can create the connection between the Nextcloud app and the Notes app.

> as I'd rather not register my private account in core Google modules

I understand and support your opinion. For this reason i do not have installed Google services on my phone at all. Obviously the app still works for me, so no need to share anything with google to use the app 😉.

However if you want to get your money refunded, mail me your Order ID to info@niedermann.it - or use the app with the only supported login method: Single Sign On with permissions which are needed for it.

**Comment by keunes** [comment]
> However since version 2.0.0 we rely on the Single Sign On mechanism of Nextcloud for many reasons like security and compatibility.

Ok, that was not the most smooth update experience. But if that's the best way to go I trust your assessment and will grant the permission :) Thanks for the support!

**Comment by stefan-niedermann** [comment]
Yeah, it was a breaking change (therefore the new major version) and we knew that we might even lose some users, but in our opinion there are more advantages than contras and so we decided to go it 🙂
