### ISSUE TITLE
Move the change title option

### ISSUE THREAD

**Issue by Bleuzen** [stefan-niedermann/nextcloud-notes#882]
(from original issue https://github.com/stefan-niedermann/nextcloud-notes/issues/881)

- [ ] **1) The change title option is hard to find for new users**
New users may try to just tap on the title to edit it. But this doesn't work. They have to search in the three-dot menu to find this option. Not very user friendly.

- [ ] **2) Changing the title are too many steps to do**
Open the note. Tap on the three-dot menu (1). Tap on change title (2). Tap on the text field to open the keyboard (3). Tap on save (4).
These are 4 steps. Let me compare this to the Google Notes app:
Open the note. Tap on the title (1). Keyboard opens automatically. No need to press save. This is much less annoying, especially when you are editing titles often.
What about doing it like Google's app? This is much more user friendly.
Example video, comparing changing title in Nextcloud Notes vs Google Keep app:
https://www.youtube.com/watch?v=YjHAYLFie34

Just move the title down (out of the title bar) to a text field above the note content.

| 1 | 2 |
| --- | --- |
| ![Screenshot_20200620-111229](https://user-images.githubusercontent.com/12885163/85198253-7185b900-b2e7-11ea-9506-fd4184219045.jpg) | ![Screenshot_20200620-111229_fixed](https://user-images.githubusercontent.com/12885163/85198867-f7a3fe80-b2eb-11ea-851f-3c435c55bdf1.png) |

**Comment by stefan-niedermann** [comment]
So, a quick win would be to also open the dialog when pressing on the note title at it's current position, right?
This would
- make it easier to find (though this is a personal opinion without user research and field tests :wink: )
- reduce the steps to edit the title

Do you agree that this would be an enhancement compared to the current state?

Moving the title to a separate field in the content area is a topic that has been discussed since the very beginning of the app (including the server app).
I still think we have a good standing here, because as a user, i don't want to care about a title, but i want to immediately start typing. I don't want to scan two fields, think about what belongs where, i just want to write. No distraction.
A user of the Notes app must be able to simply write down the first thought out of his mind. (Well, at least that's our design goal)

The title will be generated out of the first line of the note (which usually never will change - obviously we don't have any statistics because we don't have any trackers).
If a user really cares about the title, and how to change it, he will find it (especially when also clicking on the title directly will open the dialog). Once he found it, he will be able to find it again :wink:

**Comment by Bleuzen** [comment]
> So, a quick win would be to also open the dialog when pressing on the note title at it's current position, right?
> Do you agree that this would be an enhancement compared to the current state?

Well yes, in the short term, this is better than the current state.

> I still think we have a good standing here, because as a user, i don't want to care about a title, but i want to immediately start typing. I don't want to scan two fields, think about what belongs where, i just want to write. No distraction.
A user of the Notes app must be able to simply write down the first thought out of his mind. (Well, at least that's our design goal)

A little inspiration from the Google Keep app:
They have two text fields, one for title, one for content, just how I put it in the screenshot.
When creating a new note, the keyboard automatically opens and the cursor is in the content text field, so you can start writing without distraction or thinking about a title.

On Google Keep there is not need for a title. But we need a title.
One idea to solve this may be to auto generate the title from the first line on first save if no manual title is set.
This should have the best of both worlds:
 - User can easly put his own title if wanted and quickly edit it in the future
 - User can simply write content without thinking about a title first

> which usually never will change - obviously we don't have any statistics because we don't have any trackers

haha, I change titles a lot :D
This is why it annoys me and I created this issue.

---

There are more good things about moving the title down.

1) Having a long title doesn't work well currently

![Screenshot_20200620-143750](https://user-images.githubusercontent.com/12885163/85202022-e23ace80-b303-11ea-98df-77dde4fc6260.jpg)

It would get even worse when more icons are added to the header bar, for example the star for https://github.com/stefan-niedermann/nextcloud-notes/issues/883.

Moving the title down gives it much more space and the ability to display it multi-line, so this would fix it and look much nicer in my opinion.

2) You can place more useful things for quicker access in that space

If the title is gone from the header, there could be not only the star for https://github.com/stefan-niedermann/nextcloud-notes/issues/883, but for example also a delete, share and edit category button (which are currently in the three-dot menu) for quicker access.

3) It would be more visible how to and faster to edit the title

So new users will find it even faster and it makes it also faster for users already knowing how to edit the title.

**Comment by stefan-niedermann** [comment]
> One idea to solve this may be to auto generate the title from the first line on first save if no manual title is set.

This is the current state for new notes. We would need changes in the server app to achieve this (a flag which indicates whether ever a custom title has been set). Therefore you should open an issue in the [server repository](https://github.com/nextcloud/notes/issues/) for that.

There are good reasons for both variants, i think. Largely depending on how intensive one is using the title and needs to balanced with the visual noise of another visible field.

(though 2. is invalid because the space is managed by Android as [mentioned here](https://github.com/stefan-niedermann/nextcloud-notes/issues/883#issuecomment-646988487))

> haha, I change titles a lot :D

i said *usually* :laughing: 

However i currently only plan to implement the direct editing when clicking the title, sorry.

**Comment by stefan-niedermann** [comment]
We have a custom title only since the latest version, so let's see whether or not more requests regarding this topics raise, so we might reevaluate this decision in the future.

**Comment by Bleuzen** [comment]
> However i currently only plan to implement the direct editing when clicking the title, sorry.

Okay no problem, at least that makes it a little faster, this would already help.
So thanks :)

**Comment by stefan-niedermann** [comment]
Thanks though for the proposal. Glad we can improve a little bit for all users and you are not too disappointed 😉

**Comment by stefan-niedermann** [comment]
> Open the note. Tap on the three-dot menu (1). Tap on change title (2). Tap on the text field to open the keyboard (3). Tap on save (4).

So, now there are two options:

1. Click on toolbar (1), immediately edit (2)
2. Tap on the three-dot menu (1), Tap on change title (2), ~~Tap on the text field to open the keyboard~~ (keyboard will now immediately show up), Tap on save (3)

**Comment by Bleuzen** [comment]
Sounds great, thank you

**Comment by stefan-niedermann** [comment]
btw @Bleuzen are you F-Droid or Play Store Beta user?

**Comment by Bleuzen** [comment]
I'm using the app from F-Droid.

Because of testing?

**Comment by stefan-niedermann** [comment]
Yeah, i can release the app at the Play Store Beta channel immediately, but for some reasons (i guess capacity issues), F-Droid build are currently taking up to easily one week or even longer...

I can't influence this, so you will need to be a little patient until the new version will arrive you.

**Comment by stefan-niedermann** [comment]
If you are familiar with GitHub and Android, you can have a look at the "Actions" tab of GitHub though where you can find the latest builds which can be installed parallel to the F-Droid app.

**Comment by Bleuzen** [comment]
> F-Droid build are currently taking up to easily one week or even longer
This is normal since they update their live packages manually only when the maintainer(s) have time.

Anyway, I built it myself. Could have also used the CI build if I would have known earlier.

Editing title works now.
One little detail could be improved:
After saving the new title (or pressing cancel) the keyboard stays open, even if the cursor is not in a text field.

**Comment by stefan-niedermann** [comment]
Yeah, keyboard handling is a pain in the ass. It's an issue because i don't know whether it was open or closed before one starts the dialog.

PR is welcome if you know how this can be fixed 🚀
