### ISSUE TITLE
Move the fav star in grid mode

### ISSUE THREAD

**Issue by Bleuzen** [stefan-niedermann/nextcloud-notes#883]
(from original issue https://github.com/stefan-niedermann/nextcloud-notes/issues/881)

When using the phone in one handed mode, the bottom right of a tile is the best area to reach. But this is where the fav star is placed. So it is easy to accidentally fav a note instead of opening it.

Demo video:
https://www.youtube.com/watch?v=BvAaakbesmk

Someone may come up with something better, but this would be one way to solve it:
Move the star icon into the note view.

So let me take the screenshot from https://github.com/stefan-niedermann/nextcloud-notes/issues/882 again and edit it a little. If you fix https://github.com/stefan-niedermann/nextcloud-notes/issues/882, there is enough place in the title bar when in a note to place another button. So it may look like this:

| 1 | 2 |
| --- | --- |
| ![Screenshot_20200620-111229_flaw2_innote_fixed](https://user-images.githubusercontent.com/12885163/85199032-e60f2680-b2ec-11ea-91a2-b17d40046e1f.png) | ![Screenshot_20200620-115013_flaw2-grid-fixed](https://user-images.githubusercontent.com/12885163/85199044-fcb57d80-b2ec-11ea-9b08-7ee56483010d.jpg) |

Now you can remove the star icon from the grid view.

**Comment by stefan-niedermann** [comment]
I agree that the position is not ideal (i had it the top right in the beginning, but this takes away too much space from the title because Android does not allow to float text around an image easily).

I would suggest to put the star at the bottom left, because
- We still have the direct access
- It will be harder to accidentally hit
- It would be in line (feature parity and position) with the list view

Regarding your idea to make the star directly visible next to the title:

This is already the case. I told Android to display it `ifRoom` (recommended), and it is visible in landscape and on tablets (see screenshot below).

Though i'd like to keep it accessible directly on the card.

What's your opinion on putting at the bottom left of the cards?

![grafik](https://user-images.githubusercontent.com/4741199/85201774-45c3fc80-b302-11ea-9c59-9bcfab5a68b8.png)

**Comment by stefan-niedermann** [comment]
See screenshot in the Pull Request: https://github.com/stefan-niedermann/nextcloud-notes/pull/887

**Comment by Bleuzen** [comment]
I don't think https://github.com/stefan-niedermann/nextcloud-notes/pull/887 really would make it better.

1) You are just trading right handed users for left handed users.

The problem still persists, just for other users / in other scenarios.

2) Personal opinion, but I don't like the look of the star in the notes overview

Especially when these are notes without a category. Smells like wasted space. Note is higher just because of that little icon.

3) It is a Grid VIEW

A litle personal opinion again, but I think the main function for the grid view should be to display cards to tap on, not to hold features for within this cards thing, which could accidentally be activated during scrolling.

This would make opening notes more user friendly I think, because users won't have to look and think where they tap on. Just anywhere on the card will do, without activating random stuff they did not want to.

This would make it a little easier, faster and less error prone to switch between notes. Better for the user, I guess.

---

New idea: move the fav option in the long press menu.

This way, it is still toggleable from the view without opening the note first and it would remove the possibilities for accidents.

**Comment by stefan-niedermann** [comment]
> You are just trading right handed users for left handed users.

This affects each and every user interface element and is not valid therefore. (Also people can force a right-to-left layout in the android settings if this is in general disturbing)

> Personal opinion, but I don't like the look of the star in the notes overview

Well... 

> It is a Grid VIEW

Yes, and like in most other apps (e. g. Google Mail, Contacts and so on) there are quick actions available which will not cover the whole view but provide some important actions without the need to completely switch the activity.

> New idea: move the fav option in the long press menu.

Only in addition to the current quick action. If you are interested, open a separate ticket (would cause some other decisions to make, like what if i select a already favorited note and a not-favorited note)

> Also there will be a little more space in the grid for actual notes.

Also wrong if there is a category set.


It's a compromise, but design decisions are always compromises... 
We don't want to create a simple clone of Google Keep, but we have our own focus. Marking notes as favorites is a core feature and therefore reasonable directly visible (A feature which Keep doesn't have AFAIK).

**Comment by Bleuzen** [comment]
> This affects each and every user interface element and is not valid therefore. (Also people can force a right-to-left layout in the android settings if this is in general disturbing)

Yes, I didn't think of that. In this case, https://github.com/stefan-niedermann/nextcloud-notes/pull/887 should make it a little better.

> Yes, and like in most other apps (e. g. Google Mail, Contacts and so on)

Haven't found the grid view on GMail and have no other app currently on my phone that uses it (only the phone app, see example below), but as far as I can remeber when I used grid views, there was never something that directly started an action by pressing on it. Only sometimes a menu. Only example I found on my phone, this is how my phone app is handling favs:

https://www.youtube.com/watch?v=3cbsPJHkcrc

So the star is displayed in the tile, but you can not directly change the fav state from there. You have to open the three-dot menu first, which prevents from accidental trigger. I somehow like this and this is what I did remeber as for grid views.

> Only in addition to the current quick action. If you are interested, open a separate ticket (would cause some other decisions to make, like what if i select a already favorited note and a not-favorited note)

I do not thing that this would be useful if the star icon is already on the tile. So not, this would only create more work than be useful.

> We don't want to create a simple clone of Google Keep

Yes I was just using it as inspiration, because UX wise I think this app is really good. Don't try to 'just be different'. We can still take over some good ideas.

> Marking notes as favorites is a core feature and therefore reasonable directly visible (A feature which Keep doesn't have AFAIK).

Keep has this feature. But the button becomes only visible when long pressing or opening the note. In both cases the fav button is in the same place - the headerbar, which is consistant, this is why I liked it.

Anyway, let's find a possibly better solution and not just try hard to be a clone.

---

New ideas:

1) Do it like my phone app. Do not allow to directly toggle fav state from one tap.

But this would require adding a three-dot menu to every note. Someone has to think about what this menu could be used for. (Maybe also share, delete, category... ? But this is already in long press menu.)

So this solution is okay at best. But I have another idea.

2) Provide an undo function just like for deletion of notes

If someone accidentally favs / un-favs a note, there will spawn the undo bar to quickly reverse the action.
I think this could be the best compromise and solution.
Also, it adds consistency (becaus delete also has this undo bar).

What do you think about these options?

**Comment by stefan-niedermann** [comment]
About the left hander issue: The longer i think about it, the less valid is this argument. Take the main Nextcloud app as an example: right handed people could as easy tap on the share button which will them throw out of they workflow as well if it was not by intention. Phone app might even start an actual call when you tap on the right side icon instead of the name of each entry.

Hmm :thinking: 

About 1:

Would have the drawback that one cannot directly see the current favorite status (admitted, favorites are always sorted at the top)

About 2:

Delete is a very destructive operation (unlike favorite), that's why there is an undo-operation. I don't see the need to hide a non-destructive operation and make the behavior actually more unclear (*IMHO*)

The main problem i see here is, that we have this behavior for years in the list view now and no one ever mentioned in all that years that marking a note as favorite was an issue.

The grid view is actually brand new (and not even released at the Play Store release channel yet), so we can only compare with the list view unfortunately (for now).

I'd like to release the Grid view for all people and wait for some user input. If there will be other requests / issues about this topic, we can talk about it again. I think moving the star to the left of the cards should solve this issue for you (in person) that you accidentally tap on it. For everything else we simply need more information whether or not this is *really* an issue.
