### ISSUE TITLE
display notes without titles - they're not really essential

### ISSUE THREAD

**Issue by furkanunluturkk** [stefan-niedermann/nextcloud-notes#975]
_i just failed to notice the comment signs in the previous issue xD , sorry._

**Is your feature request related to a problem? Please describe.**
Most of the time a note is just a note and i just don't need to enter a title for it. But when i don't, title is automatically filled with the first line of the note. And also in the grid view I should see the sole text I wrote without the title which is copied from the first line.

**Describe the solution you'd like**
Entering a title should be optional, not essential. And notes without a title should be displayed plain vanilla in grid view.

**Comment by stefan-niedermann** [comment]
Ahaa, now i understand :smile: 

Actually the title **is** optional. What you can see in the gridview is not a truncated first line, but an `excerpt`. An excerpt is a truncated version of the whole content, currently limited to `200` characters.

This happens for various reasons, like performance and user experience (there are people with note which have a length of over 10.000 characters).

**Comment by furkanunluturkk** [comment]
oh, i see. but when i save a not without a title and then open that note i see the exact same thing which is written in the first line. that seems a bit weird to me.

**Comment by stefan-niedermann** [comment]
You mean this?

![grafik](https://user-images.githubusercontent.com/4741199/95745564-9be3f380-0c95-11eb-8167-e4bab493d4e5.png)

This is not the grid view, but you are already *editing* the note - While editing (or viewing the preview), there is a title in the toolbar.
You don't have to care about it, if you don't need a title, it will be generated by the first line of the content. But there *are* people who rely on it. Many people in fact, that's why we decided to implement it this way.

Isn't easy to satisfy each use-case of everyone :wink: 

So, what are we exactly talking about? The generated title (which is visible in the toolbar while editing)? Or the excerpt (which is a shortened version of the whole content, visible in the listview and gridview *before* selecting a note)?

**Comment by furkanunluturkk** [comment]
> You mean this?
> 
> ![grafik](https://user-images.githubusercontent.com/4741199/95745564-9be3f380-0c95-11eb-8167-e4bab493d4e5.png)
> 
> This is not the grid view, but you are already _editing_ the note - While editing (or viewing the preview), there is a title in the toolbar.
> You don't have to care about it, if you don't need a title, it will be generated by the first line of the content. But there _are_ people who rely on it. Many people in fact, that's why we decided to implement it this way.
> 
> Isn't easy to satisfy each use-case of everyone 😉
> 
> So, what are we exactly talking about? The generated title (which is visible in the toolbar while editing)? Or the excerpt (which is a shortened version of the whole content, visible in the listview and gridview _before_ selecting a note)?

wow i didn't know many people have requested for that. looks like democracy wins xd .
i was talking about the both. i think the second one depends on the first one since the generated title is displayed in the grid view.
i thought Nextcloud Notes as a quick-note tool for ideas and stuffs that just pop up your mind but appearantly it's not.
> (there are people with note which have a length of over 10.000 characters)

so, since all the questions and doubts are vanished, issue can be closed now. 👍

**Comment by stefan-niedermann** [comment]
> i thought Nextcloud Notes as a quick-note tool for ideas and stuffs that just pop up your mind but appearantly it's not.

In the first place it is 🙂 That's why we didn't implement the title as a separate field which has to be filled by a user - One can just start writing. I also didn't expect people to write large texts with it, but hey, users do always the opposite of what a developer expects 😆 

Let me try to explain my thoughts:

If there hasn't been set a title manually, this means, that the title equals the first line of the content (and this means the title equals the first line of the excerpt). It would be useles, to display a title *and* the excerpt in the gridview therefore.
Im this case we can strip the first line of the excerpt in the gridview: The result is your screenshot and matches my expection.

When opening a note, the excerpt doesn't matter - it shall only give a quick preview about what one can expect in the note, to scan it quickly. Therefore we display the content, but not the excerpt in the edit mode. For a long time the title in the edit mode was quite useless, as it always matched the first line of the content. After many many requests, we decided to make the title **optionally** editable, so one can organize the notes e.g. via sorting by title. Therefore we display the title also in the edit mode, in case one really wants to edit it (and it might not necesarrily match the first line of the content).

But input is always welcome - if something is unclwar or can get enhanced (for the majority of the users), just ask or open an issue 🙂
