### ISSUE TITLE
List editing and rendering errors

### ISSUE THREAD

**Issue by ssaring** [stefan-niedermann/nextcloud-notes#991]
First of all - thanks for this great app. I really like it's simplicity and the perfect NextCloud synchronization!

**Describe the bug**
List items are not rendered properly in the editor and the preview.

**To Reproduce**
Create a new MarkDown file and enter the following text:

```
# Header

* Item 1
* Item 2
    * Subitem 2-1
    * Subitem 2-2
```

**Expected behavior**

* Editor: the * character should be the only one list item symbol (highlighted). But there are two list items symbols instead, one list item dot and then the  * character.
* Preview: the Subitems should be displayed as list subitems. But they are not displayed with the list item dot (as the main items), they are displayed with the * character.

**Screenshots**
No screenshots created (yet), can provide them on demand.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 2.17.1
 - F-Droid or Play Store: Play Store
 - Android-Version: 11
 - Device: Pixel 5

**Comment by stefan-niedermann** [comment]
Thank you for the feedback. We are aware that there are various bugs in the current markdown rendering engine. It is unfortunately not maintained anymore, this makes it impossible for us to fix those bugs.
Therefore we [are working on replacing the markdown renderinge engine](https://github.com/stefan-niedermann/nextcloud-notes/issues/549) since quite a long time. It is unfortunately no easy task, but since we need a proper markdown rendering engine also for [Nextcloud Deck Android](https://github.com/stefan-niedermann/nextcloud-deck/pull/735), you can be sure, that we keep working on it.

Sorry that i don't have better news currently, but if you are a developer and want to join, just let me know 🙂

**Comment by ssaring** [comment]
It's nice to hear that this is work in progress - thanks for the info!
