### ISSUE TITLE
Keyboard being dismissed when app moves to background

### ISSUE THREAD

**Issue by larena1** [stefan-niedermann/nextcloud-notes#993]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
This issue has been annoying me for quite a while already. When the app moves to background and there's a note open in edit mode with the keyboard active, it will dismiss the keyboard.

That is super annoying because for instance when I make my shopping list, I use to switch between pdf viewer app and notes app and every time I must tap into the note view to continue editing.

Keyboard should not be dismissed when leaving the app. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 
 - F-Droid or Play Store: 
 - Android-Version: 
 - Device: 

**Server**
 - Nextcloud version: 
 - Nextcloud Notes version (server app): 

**Stacktrace**

**Comment by larena1** [comment]
Is it possible to fix this bug?

**Comment by stefan-niedermann** [comment]
Sure, you can contribute a Pull Request or wait until someone picks it up 🙂 This kind of questions won't help to fix it quicker, though.

**Comment by larena1** [comment]
What would there be needed? Do you think it's just a matter of saving state in onPause and conditionally calling requestFocus in onResume?

**Comment by stefan-niedermann** [comment]
I really don't know yet, maybe that's all what is needed. Give it a try, if it works i will merge it and give you a little bounty 😉

**Comment by Drhaal** [comment]
Are you still interested in this being fixed ? I can start working on it

**Comment by stefan-niedermann** [comment]
Sure, go ahead, a Pull Request will be very welcome 🙂

**Comment by larena1** [comment]
@Drhaal thanks for looking into this. Unfortunately though at least for me it's not working at all.

Using latest notes version on A10 OOS. It's still working fine in Simplenote

**Comment by stefan-niedermann** [comment]
> latest notes version

unfortunately this information is unfortunately quite useless as "latest" is different on Play Store,, AppGallery, F-Droid and other stores and we released this only a few days ago which means that it probably hasn't arrived yet on every device.

The version that ships this MR of @Drhaal is `3.4.11`. I assume `A10` means `Android 10`, but what means `OOS`?

**Comment by larena1** [comment]
Sorry, I hoped it was clear enough. By latest version I mean latest tagged version which is 3.4.11

OOS is Oxygen OS. It probably doesn't matter. Just thought I'd add it for the sake of completeness

**Comment by Drhaal** [comment]
Well since I had to use a workaround to detect the keyboard state on A10 an prior this is not totally surprising.
Although I encountered no problem with this workaround during my testing and lot of other app seem to rely on the same method.

I you could capture a debug log that might provide useful information but I'm not sure it will be enough

**Comment by stefan-niedermann** [comment]
Well since this is actually a lack of a proper API in older Android versions, i do not really see a way to improve the behavior.

I tested the fallback on an emulated Android 5 device, where it worked as expected.

If noone else has an idea how to improve the behavior despite the missing necessary Android APIs, i'll close this.

Of course Pull Requests for further enhancements are welcome!

Thanks again @Drhaal for the contribution!

**Comment by larena1** [comment]
Am on Android 11 now but the culprit seems to be gesture navigation. Keyboard won't reveal again when using it but will when using classic 3 button menu layout.
